/**
 * Content Bank — Engineering, Level 1 (Task 5.14, Batch 3).
 * Blueprint §6.3 L1 (DD20 MT15 OR10 ST15 FC10 II5 PA5 ME10 SC5 NL5),
 * topics §7.3 L1, difficulty §5.3 L1 (D1 70 / D2 25 / D3 5).
 */
import { src, dragDrop, sorting, matching, fillComplete, pattern, memory, ordering, numberLogic, scenarioChallenge } from './helpers.mjs'

const S = { level: 1, ...src('engineering') }

export default [
  dragDrop({
    items: [
      { id: 'i1', label: 'Scissors' },
      { id: 'i2', label: 'Glue stick' },
      { id: 'i3', label: 'Saw' },
      { id: 'i4', label: 'Tape' },
      { id: 'i5', label: 'Screwdriver' },
      { id: 'i6', label: 'Staples' },
    ],
    zones: [
      { id: 'z_cut', label: 'Cutting Tool' },
      { id: 'z_join', label: 'Joining Tool' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_cut' },
      { itemId: 'i2', zoneId: 'z_join' },
      { itemId: 'i3', zoneId: 'z_cut' },
      { itemId: 'i4', zoneId: 'z_join' },
      { itemId: 'i5', zoneId: 'z_join' },
      { itemId: 'i6', zoneId: 'z_join' },
    ],
    prompt: 'Classify each engineering workshop tool as a Cutting Tool or a Joining Tool.',
    explanation: 'Scissors and saws cut materials. Glue, tape, screwdrivers, and staples join materials together.',
    objective: 'Classify common workshop tools by function.',
    topic: 'materials-structures',
    subtopic: 'material-properties',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Does the tool separate material or attach pieces together?' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'Wood' },
      { id: 'i2', label: 'Plastic bottle' },
      { id: 'i3', label: 'Cotton wool' },
      { id: 'i4', label: 'Nylon fabric' },
      { id: 'i5', label: 'Granite stone' },
      { id: 'i6', label: 'Polyester rope' },
    ],
    categories: [
      { id: 'c_nat', label: 'Natural Material' },
      { id: 'c_syn', label: 'Synthetic Material' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_nat' },
      { itemId: 'i2', categoryId: 'c_syn' },
      { itemId: 'i3', categoryId: 'c_nat' },
      { itemId: 'i4', categoryId: 'c_syn' },
      { itemId: 'i5', categoryId: 'c_nat' },
      { itemId: 'i6', categoryId: 'c_syn' },
    ],
    prompt: 'Sort each material into Natural Material or Synthetic Material.',
    explanation: 'Natural materials come directly from nature (wood, cotton, stone). Synthetic materials are human-made from chemicals (plastic, nylon, polyester).',
    objective: 'Distinguish between natural and synthetic materials.',
    topic: 'materials-structures',
    subtopic: 'material-properties',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Consider whether the material is harvested from nature or created chemically.' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'Lever' },
      { id: 'l2', text: 'Inclined Plane' },
      { id: 'l3', text: 'Pulley' },
      { id: 'l4', text: 'Wheel and Axle' },
    ],
    rightItems: [
      { id: 'r1', text: 'Seesaw' },
      { id: 'r2', text: 'Wheelchair ramp' },
      { id: 'r3', text: 'Flagpole rope system' },
      { id: 'r4', text: 'Bicycle wheel' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each simple machine to its real-world example.',
    explanation: 'A seesaw is a lever, a ramp is an inclined plane, a flagpole rope uses a pulley, and a bicycle wheel is a wheel and axle.',
    objective: 'Match simple machines to everyday examples.',
    topic: 'mechanisms-machines',
    subtopic: 'simple-machines',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which simple machine pivots on a fulcrum?' }],
    ...S,
  }),

  ordering({
    items: [
      { id: 'o1', label: 'Define the problem' },
      { id: 'o2', label: 'Brainstorm solution ideas' },
      { id: 'o3', label: 'Build a prototype' },
      { id: 'o4', label: 'Test and evaluate' },
    ],
    order: ['o1', 'o2', 'o3', 'o4'],
    prompt: 'Arrange the core steps of the Engineering Design Process in correct order.',
    explanation: 'Engineers first define the problem, brainstorm ideas, build a physical prototype, and finally test and evaluate it.',
    objective: 'Order the stages of the engineering design process.',
    topic: 'design-process',
    subtopic: 'define-problem',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'You must understand the problem before thinking of solutions.' }],
    ...S,
  }),

  fillComplete({
    template: 'A triangular shape is commonly used in bridge trusses because it is very ___ under load.',
    blanks: [{ id: 'b1', type: 'text', label: 'property', maxLength: 10 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['strong', 'stable', 'rigid'] }],
    prompt: 'A triangular shape is commonly used in bridge trusses because it is very ___ under load.',
    explanation: 'Triangles do not easily deform under load, making them inherently strong and stable structural units.',
    objective: 'Identify the structural strength of triangular shapes.',
    topic: 'materials-structures',
    subtopic: 'structures-stability',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Think about how rigid a triangle is compared to a square.' }],
    ...S,
  }),

  memory({
    cards: [
      { id: 'c1', text: 'Battery' },
      { id: 'c2', text: 'Power source' },
      { id: 'c3', text: 'Switch' },
      { id: 'c4', text: 'Opens/closes circuit' },
      { id: 'c5', text: 'Light bulb' },
      { id: 'c6', text: 'Light output' },
      { id: 'c7', text: 'Wire' },
      { id: 'c8', text: 'Conducts current' },
    ],
    groups: [
      { groupId: 'g1', cardIds: ['c1', 'c2'] },
      { groupId: 'g2', cardIds: ['c3', 'c4'] },
      { groupId: 'g3', cardIds: ['c5', 'c6'] },
      { groupId: 'g4', cardIds: ['c7', 'c8'] },
    ],
    revealSeconds: 12,
    recallPrompt: 'Remember each electrical component with its role.',
    deckType: 'pairs',
    prompt: 'Memorise each electrical component with its role, then match the pairs.',
    explanation: 'Batteries provide power, switches control flow, light bulbs produce light, and wires conduct current.',
    objective: 'Match basic circuit components to their functions.',
    topic: 'electronics-circuits',
    subtopic: 'basic-circuits',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Pair the part with what it does in a circuit.' }],
    ...S,
  }),

  pattern({
    sequence: [
      { id: 'e1', text: 'Gear 1: Clockwise' },
      { id: 'e2', text: 'Gear 2: Counter-clockwise' },
      { id: 'e3', text: 'Gear 3: Clockwise' },
      { id: 'e4', text: 'Gear 4: Counter-clockwise' },
    ],
    interaction: 'complete-sequence',
    candidates: [
      { id: 'c1', text: 'Gear 5: Clockwise' },
      { id: 'c2', text: 'Gear 5: Counter-clockwise' },
      { id: 'c3', text: 'Gear 5: Stopped' },
      { id: 'c4', text: 'Gear 5: Upward' },
    ],
    answer: { type: 'candidate', rule: 'Meshed gears alternate rotation direction.', acceptableIds: ['c1'] },
    prompt: 'In a line of meshed spur gears, Gear 1 turns Clockwise. Predict the direction of Gear 5.',
    explanation: 'Adjacent meshed gears turn in opposite directions, so odd-numbered gears turn clockwise.',
    objective: 'Predict gear rotation direction in a gear train.',
    topic: 'mechanisms-machines',
    subtopic: 'levers-pulleys-gears',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Notice how the direction alternates with each gear in line.' }],
    ...S,
  }),

  numberLogic({
    problem: 'A single moveable pulley halves the effort needed to lift a load. If the load weighs 20 N, how many newtons of effort are required?',
    answerFormat: 'integer',
    answer: { type: 'exact', value: 10 },
    prompt: 'A single moveable pulley halves the effort needed to lift a load. If the load weighs 20 N, how many newtons of effort are required?',
    explanation: '20 N ÷ 2 = 10 N of effort force needed.',
    objective: 'Calculate effort force with mechanical advantage.',
    topic: 'mechanisms-machines',
    subtopic: 'simple-machines',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Divide the load force by 2.' }],
    ...S,
  }),

  scenarioChallenge({
    scenario: 'An engineering team needs to build a pedestrian bridge over a narrow creek using natural stone available at the site. Which design takes advantage of stone\'s high compressive strength?',
    options: [
      { id: 'opt1', text: 'Stone Arch Bridge' },
      { id: 'opt2', text: 'Paper Suspension Bridge' },
      { id: 'opt3', text: 'Glass Beam Bridge' },
      { id: 'opt4', text: 'Plastic Straw Bridge' },
    ],
    correctOptionId: 'opt1',
    prompt: 'Choose the bridge design best suited for natural stone.',
    explanation: 'Stones perform exceptionally well under compression in an arch structure, where gravity wedges the stones tightly together.',
    objective: 'Select an appropriate structural design for given material properties.',
    topic: 'materials-structures',
    subtopic: 'structures-stability',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Arches push structural blocks together under compression.' }],
    ...S,
  }),

  dragDrop({
    items: [
      { id: 'i1', label: 'Pressing a doorbell' },
      { id: 'i2', label: 'Opening a sliding drawer' },
      { id: 'i3', label: 'Stamping a document' },
      { id: 'i4', label: 'Dragging a suitcase' },
      { id: 'i5', label: 'Pushing a shopping cart' },
      { id: 'i6', label: 'Tugging a rope' },
    ],
    zones: [
      { id: 'z_push', label: 'Push Force' },
      { id: 'z_pull', label: 'Pull Force' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_push' },
      { itemId: 'i2', zoneId: 'z_pull' },
      { itemId: 'i3', zoneId: 'z_push' },
      { itemId: 'i4', zoneId: 'z_pull' },
      { itemId: 'i5', zoneId: 'z_push' },
      { itemId: 'i6', zoneId: 'z_pull' },
    ],
    prompt: 'Classify each action as applying a Push Force or a Pull Force.',
    explanation: 'Push forces move objects away from you (doorbell, stamp, shopping cart). Pull forces move objects toward you (drawer, suitcase, rope).',
    objective: 'Classify mechanical forces as push or pull.',
    topic: 'materials-structures',
    subtopic: 'forces-in-structures',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Are you moving the object away from yourself or towards yourself?' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'DC Battery Symbol' },
      { id: 'l2', text: 'Light Bulb Symbol' },
      { id: 'l3', text: 'Switch Symbol' },
      { id: 'l4', text: 'Resistor Symbol' },
    ],
    rightItems: [
      { id: 'r1', text: 'Voltage Energy Source' },
      { id: 'r2', text: 'Light Output Element' },
      { id: 'r3', text: 'Circuit Controller' },
      { id: 'r4', text: 'Current Limiter' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each schematic symbol concept to its electrical function.',
    explanation: 'Batteries supply voltage, light bulbs convert electricity to light, switches control connection, and resistors limit current flow.',
    objective: 'Relate schematic circuit components to functions.',
    topic: 'electronics-circuits',
    subtopic: 'components',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which component limits how much electrical current flows?' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'Measuring beam deflection in lab' },
      { id: 'i2', label: 'Lubricating worn motor gears' },
      { id: 'i3', label: 'Testing circuit voltage on prototype' },
      { id: 'i4', label: 'Replacing broken light bulb in user building' },
      { id: 'i5', label: 'Drop testing prototype casing' },
      { id: 'i6', label: 'Cleaning solar panel surface' },
    ],
    categories: [
      { id: 'c_test', label: 'Prototype Testing' },
      { id: 'c_maint', label: 'Routine Maintenance' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_test' },
      { itemId: 'i2', categoryId: 'c_maint' },
      { itemId: 'i3', categoryId: 'c_test' },
      { itemId: 'i4', categoryId: 'c_maint' },
      { itemId: 'i5', categoryId: 'c_test' },
      { itemId: 'i6', categoryId: 'c_maint' },
    ],
    prompt: 'Sort each engineering activity into Prototype Testing or Routine Maintenance.',
    explanation: 'Testing activities measure prototype performance during design. Maintenance activities service existing operational equipment.',
    objective: 'Distinguish between testing prototypes and servicing operational systems.',
    topic: 'design-process',
    subtopic: 'test-evaluate',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Is the activity gathering data on a new design or maintaining an existing product?' }],
    ...S,
  }),

  fillComplete({
    template: 'Solar panels convert energy from sunlight directly into ___ energy.',
    blanks: [{ id: 'b1', type: 'text', label: 'energy type', maxLength: 12 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['electrical', 'electric', 'electricity'] }],
    prompt: 'Solar panels convert energy from sunlight directly into ___ energy.',
    explanation: 'Photovoltaic solar cells convert radiant light energy directly into electrical energy.',
    objective: 'Identify energy conversion in solar panels.',
    topic: 'systems-society',
    subtopic: 'energy-systems',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'What form of energy powers household lights and appliances?' }],
    ...S,
  }),

  ordering({
    items: [
      { id: 'o1', label: 'Collect plastic waste' },
      { id: 'o2', label: 'Sort by plastic resin type' },
      { id: 'o3', label: 'Shred plastic into flakes' },
      { id: 'o4', label: 'Melt and mold into new products' },
    ],
    order: ['o1', 'o2', 'o3', 'o4'],
    prompt: 'Arrange the steps for recycling plastic into new engineering products.',
    explanation: 'Waste is collected, sorted by material type, shredded into small flakes, and finally melted to mold new items.',
    objective: 'Order the steps of plastic recycling for sustainable design.',
    topic: 'systems-society',
    subtopic: 'sustainable-design',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Sorting must happen before shredding different plastics together.' }],
    ...S,
  }),
]
