/**
 * Content Bank — Science, Level 3 (Task 5.14, Batch 1).
 * Blueprint §6.1 L3 (DD15 MT10 OR10 ST10 FC15 II15 PA5 ME10 SC5 NL5),
 * topics §7.3 L3, difficulty §5.3 L3 (D1 30 / D2 40 / D3 25 / D4 5).
 */
import { src, dragDrop, sorting, matching, fillComplete, imageInteraction, pattern, memory, numberLogic, scenario, ordering } from './helpers.mjs'

const S = { level: 3, ...src('science') }

export default [
  dragDrop({ items: [{ id: 'i1', label: 'Lemon juice' }, { id: 'i2', label: 'Soap' }, { id: 'i3', label: 'Vinegar' }, { id: 'i4', label: 'Baking soda' }, { id: 'i5', label: 'Milk' }, { id: 'i6', label: 'Pure water' }], zones: [{ id: 'z_a', label: 'Acidic' }, { id: 'z_b', label: 'Basic' }, { id: 'z_n', label: 'Neutral' }], mappings: [{ itemId: 'i1', zoneId: 'z_a' }, { itemId: 'i2', zoneId: 'z_b' }, { itemId: 'i3', zoneId: 'z_a' }, { itemId: 'i4', zoneId: 'z_b' }, { itemId: 'i5', zoneId: 'z_n' }, { itemId: 'i6', zoneId: 'z_n' }], prompt: 'Classify each substance as acidic, basic or neutral.', explanation: 'Lemon juice and vinegar are acids, soap and baking soda are bases, and milk and pure water are near-neutral.', objective: 'Classify everyday substances by pH.', topic: 'chemistry', subtopic: 'acids-bases', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Acids taste sour; bases feel slippery.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Iron' }, { id: 'i2', label: 'Oxygen' }, { id: 'i3', label: 'Copper' }, { id: 'i4', label: 'Carbon' }, { id: 'i5', label: 'Gold' }, { id: 'i6', label: 'Sulfur' }], zones: [{ id: 'z_m', label: 'Metal' }, { id: 'z_nm', label: 'Non-metal' }], mappings: [{ itemId: 'i1', zoneId: 'z_m' }, { itemId: 'i2', zoneId: 'z_nm' }, { itemId: 'i3', zoneId: 'z_m' }, { itemId: 'i4', zoneId: 'z_nm' }, { itemId: 'i5', zoneId: 'z_m' }, { itemId: 'i6', zoneId: 'z_nm' }], prompt: 'Classify each element as a metal or a non-metal.', explanation: 'Iron, copper and gold are metals; oxygen, carbon and sulfur are non-metals.', objective: 'Classify elements as metals or non-metals.', topic: 'chemistry', subtopic: 'periodic-table', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Metals are shiny and conduct electricity well.' }], ...S }),

  sorting({ items: [{ id: 'i1', label: 'Circulatory' }, { id: 'i2', label: 'Respiratory' }, { id: 'i3', label: 'Digestive' }, { id: 'i4', label: 'Nervous' }, { id: 'i5', label: 'Skeletal' }], categories: [{ id: 'c_blood', label: 'Transports blood' }, { id: 'c_gas', label: 'Gas exchange' }, { id: 'c_food', label: 'Breaks down food' }, { id: 'c_sig', label: 'Sends signals' }, { id: 'c_sup', label: 'Supports the body' }], assignments: [{ itemId: 'i1', categoryId: 'c_blood' }, { itemId: 'i2', categoryId: 'c_gas' }, { itemId: 'i3', categoryId: 'c_food' }, { itemId: 'i4', categoryId: 'c_sig' }, { itemId: 'i5', categoryId: 'c_sup' }], prompt: 'Sort each body system into the job it does.', explanation: 'The circulatory system transports blood, the respiratory system exchanges gases, the digestive system breaks down food, the nervous system sends signals and the skeletal system supports the body.', objective: 'Match body systems to their functions.', topic: 'life', subtopic: 'body-systems', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Read the job first, then find the system that does it.' }], ...S }),

  matching({ leftItems: [{ id: 'l1', text: 'Nucleus' }, { id: 'l2', text: 'Mitochondria' }, { id: 'l3', text: 'Cell membrane' }, { id: 'l4', text: 'Cytoplasm' }], rightItems: [{ id: 'r1', text: 'Controls the cell' }, { id: 'r2', text: 'Releases energy' }, { id: 'r3', text: 'Controls what enters' }, { id: 'r4', text: 'Jelly-like filling' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each cell part to its function.', explanation: 'The nucleus controls the cell, mitochondria release energy, the membrane controls what enters and the cytoplasm is the jelly-like filling.', objective: 'Match cell organelles to their functions.', topic: 'life', subtopic: 'cells-organisms', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think of the nucleus as the brain of the cell.' }], ...S }),

  ordering({ items: [{ id: 'o1', label: 'Form a hypothesis' }, { id: 'o2', label: 'Observe a phenomenon' }, { id: 'o3', label: 'Test the hypothesis' }, { id: 'o4', label: 'Draw a conclusion' }, { id: 'o5', label: 'Ask a question' }], order: ['o2', 'o5', 'o1', 'o3', 'o4'], prompt: 'Arrange the steps of the scientific method in order.', explanation: 'Observe → ask a question → form a hypothesis → test → draw a conclusion.', objective: 'Order the scientific method steps.', topic: 'inquiry', subtopic: 'scientific-method', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'A hypothesis comes before you test it.' }], ...S }),

  fillComplete({ template: 'The force that pulls objects toward the Earth is called ___.', blanks: [{ id: 'b1', type: 'text', label: 'force', maxLength: 12 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['gravity'] }], prompt: 'The force that pulls objects toward the Earth is called ___.', explanation: 'Gravity is the attraction between masses; the Earth pulls objects toward its centre.', objective: 'Name the force pulling objects to Earth.', topic: 'physics', subtopic: 'forces-motion', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is why objects fall downward.' }], ...S }),
  fillComplete({ template: 'A material that allows most light to pass through is called ___.', blanks: [{ id: 'b1', type: 'text', label: 'material type', maxLength: 16 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['transparent'] }], prompt: 'A material that allows most light to pass through is called ___.', explanation: 'Transparent materials let most light through, so you can see through them clearly.', objective: 'Name the property of transmitting light.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Glass is a good example.' }], ...S }),
  fillComplete({ template: 'The smallest unit of an element that keeps its chemical behaviour is an ___.', blanks: [{ id: 'b1', type: 'text', label: 'particle', maxLength: 10 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['atom'] }], prompt: 'The smallest unit of an element that keeps its chemical behaviour is an ___.', explanation: 'An atom is the smallest particle of an element that still behaves like that element.', objective: 'Define an atom.', topic: 'chemistry', subtopic: 'matter-particles', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Everything is made of these tiny particles.' }], ...S }),

  imageInteraction({ image: { ref: 'question-media/science/earth-space/earth-layers.png', alt: 'Cross-section of the Earth with labelled concentric layers, crust on the outside.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'The crust', x: 50, y: 6, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The diagram shows the layers of the Earth. Tap the crust.', explanation: 'The crust is the thin outer layer of the Earth shown at the rim of the cross-section.', objective: 'Identify the Earth’s crust in a diagram.', topic: 'earth-space', subtopic: 'earth-structure', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is the outermost layer you would walk on.' }], ...S }),

  pattern({ sequence: [{ id: 'e1', text: 'Seed' }, { id: 'e2', text: 'Sprout' }, { id: 'e3', text: 'Seedling' }], interaction: 'complete-sequence', candidates: [{ id: 'c1', text: 'Plant' }, { id: 'c2', text: 'Root' }, { id: 'c3', text: 'Fruit' }, { id: 'c4', text: 'Petal' }], answer: { type: 'candidate', rule: 'The growth of a plant.', acceptableIds: ['c1'] }, prompt: 'Choose the next stage: Seed, Sprout, Seedling, …', explanation: 'A seed grows into a sprout, then a seedling, then a full plant.', objective: 'Order the growth stages of a plant.', topic: 'life', subtopic: 'plants-animals', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Each stage is bigger and more developed.' }], ...S }),

  memory({ cards: [{ id: 'c1', text: 'Force' }, { id: 'c2', text: 'Push or pull' }, { id: 'c3', text: 'Gravity' }, { id: 'c4', text: 'Pulls downward' }, { id: 'c5', text: 'Friction' }, { id: 'c6', text: 'Slows motion' }, { id: 'c7', text: 'Magnetism' }, { id: 'c8', text: 'Attracts iron' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each force with its effect.', deckType: 'pairs', prompt: 'Memorise each force with its effect, then match the pairs.', explanation: 'A force is a push or pull, gravity pulls downward, friction slows motion and magnetism attracts iron.', objective: 'Recall key facts about forces.', topic: 'physics', subtopic: 'forces-motion', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Each pair links a force to its effect.' }], ...S }),

  numberLogic({ problem: 'A car travels 60 km in 2 hours. What is its average speed?', answerFormat: 'integer', answer: { type: 'exact', value: 30 }, prompt: 'A car travels 60 km in 2 hours. What is its average speed in km/h?', explanation: 'Speed = distance ÷ time = 60 ÷ 2 = 30 km/h.', objective: 'Calculate average speed.', topic: 'inquiry', subtopic: 'measurement-units', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Divide the distance by the time.' }], ...S }),
  numberLogic({ problem: 'A solution of pH 3 is how many times more acidic than a solution of pH 5?', answerFormat: 'integer', answer: { type: 'exact', value: 100 }, prompt: 'A solution of pH 3 is how many times more acidic than a solution of pH 5?', explanation: 'Each pH unit is ten times more acidic, so two units means 10 × 10 = 100 times.', objective: 'Compare acidity using the pH scale.', topic: 'chemistry', subtopic: 'acids-bases', difficulty: 4, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Each step of 1 on the pH scale is a tenfold change.' }], ...S }),

  scenario({
    scenarioText: 'During a lab experiment you accidentally knock over a beaker and a clear liquid spills across the bench.',
    entryDecision: 'd1',
    decisions: [
      { id: 'd1', text: 'What should you do first?', options: [
        { id: 'opt_tell', text: 'Tell the teacher immediately', nextDecision: null, outcomeText: 'The teacher assesses the spill and directs the safe cleanup — the correct choice.' },
        { id: 'opt_hand', text: 'Wipe it up with your hand', nextDecision: null, outcomeText: 'Touching an unknown liquid can be dangerous.' },
        { id: 'opt_sink', text: 'Pour it down the sink', nextDecision: null, outcomeText: 'Unknown chemicals must never be poured away without instructions.' },
      ] },
    ],
    optimalPath: [{ decisionId: 'd1', optionId: 'opt_tell' }],
    prompt: 'Choose the safest action for a chemical spill.',
    explanation: 'The safe response to any unknown spill is to alert a teacher, who will direct the correct cleanup.',
    objective: 'Apply safe lab behaviour to a spill.',
    topic: 'inquiry', subtopic: 'lab-safety', difficulty: 2, gradeMin: 7, gradeMax: 9,
    hints: [{ level: 1, text: 'Never touch or dispose of unknown substances.' }], ...S,
  }),

  dragDrop({ items: [{ id: 'i1', label: 'Kicking a ball' }, { id: 'i2', label: 'Pulling a drawer' }, { id: 'i3', label: 'Pushing a door' }, { id: 'i4', label: 'Stretching a rubber band' }, { id: 'i5', label: 'Pressing a button' }, { id: 'i6', label: 'Hoisting a flag' }], zones: [{ id: 'z_push', label: 'Push' }, { id: 'z_pull', label: 'Pull' }], mappings: [{ itemId: 'i1', zoneId: 'z_push' }, { itemId: 'i2', zoneId: 'z_pull' }, { itemId: 'i3', zoneId: 'z_push' }, { itemId: 'i4', zoneId: 'z_pull' }, { itemId: 'i5', zoneId: 'z_push' }, { itemId: 'i6', zoneId: 'z_pull' }], prompt: 'Sort each action into the force effect it shows: a push or a pull.', explanation: 'Kicking a ball, pushing a door and pressing a button push objects away, while pulling a drawer, stretching a band and hoisting a flag pull objects closer.', objective: 'Classify everyday actions as pushes or pulls.', topic: 'physics', subtopic: 'forces-motion', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'A push moves an object away from you; a pull brings it closer.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Ice' }, { id: 'i2', label: 'Steam' }, { id: 'i3', label: 'Milk' }, { id: 'i4', label: 'Oxygen' }, { id: 'i5', label: 'Stone' }, { id: 'i6', label: 'Water' }], zones: [{ id: 'z_s', label: 'Solid' }, { id: 'z_l', label: 'Liquid' }, { id: 'z_g', label: 'Gas' }], mappings: [{ itemId: 'i1', zoneId: 'z_s' }, { itemId: 'i2', zoneId: 'z_g' }, { itemId: 'i3', zoneId: 'z_l' }, { itemId: 'i4', zoneId: 'z_g' }, { itemId: 'i5', zoneId: 'z_s' }, { itemId: 'i6', zoneId: 'z_l' }], prompt: 'Group each material by the state of matter it is in at room temperature.', explanation: 'Ice and stone are solids, milk and water are liquids, and steam and oxygen are gases.', objective: 'Classify materials by state of matter.', topic: 'physics', subtopic: 'matter', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Solids keep their shape; gases fill their container.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Window glass' }, { id: 'i2', label: 'Frosted glass' }, { id: 'i3', label: 'Wooden door' }, { id: 'i4', label: 'Clean water' }, { id: 'i5', label: 'Wax paper' }, { id: 'i6', label: 'Brick wall' }], zones: [{ id: 'z_tr', label: 'Transparent' }, { id: 'z_tl', label: 'Translucent' }, { id: 'z_op', label: 'Opaque' }], mappings: [{ itemId: 'i1', zoneId: 'z_tr' }, { itemId: 'i2', zoneId: 'z_tl' }, { itemId: 'i3', zoneId: 'z_op' }, { itemId: 'i4', zoneId: 'z_tr' }, { itemId: 'i5', zoneId: 'z_tl' }, { itemId: 'i6', zoneId: 'z_op' }], prompt: 'Place each material into the group that describes how much light passes through it.', explanation: 'Window glass and clean water are transparent, frosted glass and wax paper are translucent, and a wooden door and brick wall are opaque.', objective: 'Classify materials by light transmission.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think about whether you can see clearly through the material.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Copper wire' }, { id: 'i2', label: 'Rubber glove' }, { id: 'i3', label: 'Steel nail' }, { id: 'i4', label: 'Glass rod' }, { id: 'i5', label: 'Salt water' }, { id: 'i6', label: 'Plastic spoon' }], zones: [{ id: 'z_c', label: 'Conductor' }, { id: 'z_i', label: 'Insulator' }], mappings: [{ itemId: 'i1', zoneId: 'z_c' }, { itemId: 'i2', zoneId: 'z_i' }, { itemId: 'i3', zoneId: 'z_c' }, { itemId: 'i4', zoneId: 'z_i' }, { itemId: 'i5', zoneId: 'z_c' }, { itemId: 'i6', zoneId: 'z_i' }], prompt: 'Sort each material as a conductor or an insulator of electricity.', explanation: 'Copper, steel and salt water conduct electricity, while rubber, glass and plastic do not.', objective: 'Classify materials as conductors or insulators.', topic: 'physics', subtopic: 'electricity-magnetism', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Metals and salty solutions usually conduct; plastic and rubber usually do not.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Melting ice' }, { id: 'i2', label: 'Burning wood' }, { id: 'i3', label: 'Rusting iron' }, { id: 'i4', label: 'Dissolving sugar' }, { id: 'i5', label: 'Frying an egg' }, { id: 'i6', label: 'Cutting paper' }], zones: [{ id: 'z_p', label: 'Physical change' }, { id: 'z_c', label: 'Chemical change' }], mappings: [{ itemId: 'i1', zoneId: 'z_p' }, { itemId: 'i2', zoneId: 'z_c' }, { itemId: 'i3', zoneId: 'z_c' }, { itemId: 'i4', zoneId: 'z_p' }, { itemId: 'i5', zoneId: 'z_c' }, { itemId: 'i6', zoneId: 'z_p' }], prompt: 'Classify each change as physical or chemical.', explanation: 'Melting, dissolving and cutting change shape or state without forming new substances, while burning, rusting and frying form new substances.', objective: 'Distinguish physical and chemical changes.', topic: 'chemistry', subtopic: 'reactions-changes', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'A chemical change produces a new substance.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Oxygen' }, { id: 'i2', label: 'Water' }, { id: 'i3', label: 'Salt water' }, { id: 'i4', label: 'Gold' }, { id: 'i5', label: 'Carbon dioxide' }, { id: 'i6', label: 'Air' }], zones: [{ id: 'z_e', label: 'Element' }, { id: 'z_c', label: 'Compound' }, { id: 'z_m', label: 'Mixture' }], mappings: [{ itemId: 'i1', zoneId: 'z_e' }, { itemId: 'i2', zoneId: 'z_c' }, { itemId: 'i3', zoneId: 'z_m' }, { itemId: 'i4', zoneId: 'z_e' }, { itemId: 'i5', zoneId: 'z_c' }, { itemId: 'i6', zoneId: 'z_m' }], prompt: 'Sort each material as an element, a compound or a mixture.', explanation: 'Oxygen and gold are elements, water and carbon dioxide are compounds, and salt water and air are mixtures.', objective: 'Classify materials as elements, compounds or mixtures.', topic: 'chemistry', subtopic: 'matter-particles', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Elements hold one atom type; compounds join different atoms chemically.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Frog' }, { id: 'i2', label: 'Snail' }, { id: 'i3', label: 'Eagle' }, { id: 'i4', label: 'Jellyfish' }, { id: 'i5', label: 'Snake' }, { id: 'i6', label: 'Crab' }], zones: [{ id: 'z_v', label: 'Vertebrate' }, { id: 'z_i', label: 'Invertebrate' }], mappings: [{ itemId: 'i1', zoneId: 'z_v' }, { itemId: 'i2', zoneId: 'z_i' }, { itemId: 'i3', zoneId: 'z_v' }, { itemId: 'i4', zoneId: 'z_i' }, { itemId: 'i5', zoneId: 'z_v' }, { itemId: 'i6', zoneId: 'z_i' }], prompt: 'Group each animal as a vertebrate or an invertebrate.', explanation: 'Frogs, eagles and snakes have backbones, while snails, jellyfish and crabs do not.', objective: 'Classify animals by presence of a backbone.', topic: 'life', subtopic: 'plants-animals', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'A vertebrate has a backbone or spine.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Eye colour' }, { id: 'i2', label: 'Riding a bike' }, { id: 'i3', label: 'Hair colour' }, { id: 'i4', label: 'Scar from a cut' }, { id: 'i5', label: 'Blood type' }, { id: 'i6', label: 'Speaking a language' }], zones: [{ id: 'z_i', label: 'Inherited' }, { id: 'z_a', label: 'Acquired' }], mappings: [{ itemId: 'i1', zoneId: 'z_i' }, { itemId: 'i2', zoneId: 'z_a' }, { itemId: 'i3', zoneId: 'z_i' }, { itemId: 'i4', zoneId: 'z_a' }, { itemId: 'i5', zoneId: 'z_i' }, { itemId: 'i6', zoneId: 'z_a' }], prompt: 'Sort each trait as inherited or acquired during life.', explanation: 'Eye colour, hair colour and blood type are inherited, while riding a bike, scars and language come from experience.', objective: 'Distinguish inherited traits from acquired traits.', topic: 'life', subtopic: 'genetics-heredity', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Inherited traits are passed down in DNA from parents.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Grass' }, { id: 'i2', label: 'Deer' }, { id: 'i3', label: 'Mushroom' }, { id: 'i4', label: 'Algae' }, { id: 'i5', label: 'Lion' }, { id: 'i6', label: 'Earthworm' }], zones: [{ id: 'z_p', label: 'Producer' }, { id: 'z_c', label: 'Consumer' }, { id: 'z_d', label: 'Decomposer' }], mappings: [{ itemId: 'i1', zoneId: 'z_p' }, { itemId: 'i2', zoneId: 'z_c' }, { itemId: 'i3', zoneId: 'z_d' }, { itemId: 'i4', zoneId: 'z_p' }, { itemId: 'i5', zoneId: 'z_c' }, { itemId: 'i6', zoneId: 'z_d' }], prompt: 'Classify each organism by its role in a food chain.', explanation: 'Grass and algae make their own food, deer and lions eat other organisms, and mushrooms and earthworms break down dead matter.', objective: 'Classify organisms by feeding role.', topic: 'life', subtopic: 'evolution-ecosystems', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Producers make food; consumers eat others; decomposers recycle matter.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Amoeba' }, { id: 'i2', label: 'Human' }, { id: 'i3', label: 'Bacteria' }, { id: 'i4', label: 'Oak tree' }, { id: 'i5', label: 'Paramecium' }, { id: 'i6', label: 'Dog' }], zones: [{ id: 'z_u', label: 'Unicellular' }, { id: 'z_m', label: 'Multicellular' }], mappings: [{ itemId: 'i1', zoneId: 'z_u' }, { itemId: 'i2', zoneId: 'z_m' }, { itemId: 'i3', zoneId: 'z_u' }, { itemId: 'i4', zoneId: 'z_m' }, { itemId: 'i5', zoneId: 'z_u' }, { itemId: 'i6', zoneId: 'z_m' }], prompt: 'Group each organism as single-celled or many-celled.', explanation: 'Amoebas, bacteria and paramecia are single-celled, while humans, oak trees and dogs are many-celled.', objective: 'Classify organisms as unicellular or multicellular.', topic: 'life', subtopic: 'cells-organisms', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Unicellular means one cell makes up the whole organism.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Solar energy' }, { id: 'i2', label: 'Coal' }, { id: 'i3', label: 'Wind' }, { id: 'i4', label: 'Oil' }, { id: 'i5', label: 'Wood' }, { id: 'i6', label: 'Natural gas' }], zones: [{ id: 'z_r', label: 'Renewable' }, { id: 'z_n', label: 'Non-renewable' }], mappings: [{ itemId: 'i1', zoneId: 'z_r' }, { itemId: 'i2', zoneId: 'z_n' }, { itemId: 'i3', zoneId: 'z_r' }, { itemId: 'i4', zoneId: 'z_n' }, { itemId: 'i5', zoneId: 'z_r' }, { itemId: 'i6', zoneId: 'z_n' }], prompt: 'Sort each energy resource as renewable or non-renewable.', explanation: 'Solar, wind and wood are replaced naturally, while coal, oil and natural gas are used faster than they form.', objective: 'Classify energy resources as renewable or non-renewable.', topic: 'earth-space', subtopic: 'natural-resources', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think about whether the resource can be replaced within a human lifetime.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Granite' }, { id: 'i2', label: 'Limestone' }, { id: 'i3', label: 'Marble' }, { id: 'i4', label: 'Basalt' }, { id: 'i5', label: 'Sandstone' }, { id: 'i6', label: 'Slate' }], zones: [{ id: 'z_i', label: 'Igneous' }, { id: 'z_s', label: 'Sedimentary' }, { id: 'z_m', label: 'Metamorphic' }], mappings: [{ itemId: 'i1', zoneId: 'z_i' }, { itemId: 'i2', zoneId: 'z_s' }, { itemId: 'i3', zoneId: 'z_m' }, { itemId: 'i4', zoneId: 'z_i' }, { itemId: 'i5', zoneId: 'z_s' }, { itemId: 'i6', zoneId: 'z_m' }], prompt: 'Classify each rock by the type of rock it is.', explanation: 'Granite and basalt form from cooled magma, limestone and sandstone form from layered sediment, and marble and slate form under heat and pressure.', objective: 'Classify rocks into igneous, sedimentary and metamorphic types.', topic: 'earth-space', subtopic: 'rock-cycle', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Match the rock to how it formed: cooling, layering, or heat and pressure.' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Today it is rainy' }, { id: 'i2', label: 'Deserts stay dry' }, { id: 'i3', label: 'The storm lasted an hour' }, { id: 'i4', label: 'Winters are cold here' }, { id: 'i5', label: 'A sunny afternoon' }, { id: 'i6', label: 'Tropical regions stay hot' }], zones: [{ id: 'z_w', label: 'Weather' }, { id: 'z_c', label: 'Climate' }], mappings: [{ itemId: 'i1', zoneId: 'z_w' }, { itemId: 'i2', zoneId: 'z_c' }, { itemId: 'i3', zoneId: 'z_w' }, { itemId: 'i4', zoneId: 'z_c' }, { itemId: 'i5', zoneId: 'z_w' }, { itemId: 'i6', zoneId: 'z_c' }], prompt: 'Sort each statement as describing weather or climate.', explanation: 'Short-term conditions like rain, storms and sunny afternoons are weather, while long-term patterns like dry deserts, cold winters and hot tropics are climate.', objective: 'Distinguish weather from climate.', topic: 'earth-space', subtopic: 'weather-climate', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Weather is day to day; climate is over many years.' }], ...S }),

  sorting({ items: [{ id: 'i1', label: 'A moving car' }, { id: 'i2', label: 'A stretched spring' }, { id: 'i3', label: 'A glowing fire' }, { id: 'i4', label: 'A rolling ball' }, { id: 'i5', label: 'A book on a shelf' }, { id: 'i6', label: 'Boiling water' }], categories: [{ id: 'c_kin', label: 'Kinetic energy' }, { id: 'c_pot', label: 'Potential energy' }, { id: 'c_th', label: 'Thermal energy' }], assignments: [{ itemId: 'i1', categoryId: 'c_kin' }, { itemId: 'i2', categoryId: 'c_pot' }, { itemId: 'i3', categoryId: 'c_th' }, { itemId: 'i4', categoryId: 'c_kin' }, { itemId: 'i5', categoryId: 'c_pot' }, { itemId: 'i6', categoryId: 'c_th' }], prompt: 'Sort each example into the kind of energy it shows.', explanation: 'A moving car and rolling ball hold kinetic energy, a stretched spring and raised book store potential energy, and a fire and boiling water give thermal energy.', objective: 'Classify examples of kinetic, potential and thermal energy.', topic: 'physics', subtopic: 'energy', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Kinetic means moving; potential means stored.' }], ...S }),
  sorting({ items: [{ id: 'i1', label: 'Steel spoon' }, { id: 'i2', label: 'Aluminium can' }, { id: 'i3', label: 'Paper clip' }, { id: 'i4', label: 'Copper coin' }, { id: 'i5', label: 'Refrigerator door' }, { id: 'i6', label: 'Plastic bottle' }], categories: [{ id: 'c_mag', label: 'Magnetic' }, { id: 'c_nmag', label: 'Non-magnetic' }], assignments: [{ itemId: 'i1', categoryId: 'c_mag' }, { itemId: 'i2', categoryId: 'c_nmag' }, { itemId: 'i3', categoryId: 'c_mag' }, { itemId: 'i4', categoryId: 'c_nmag' }, { itemId: 'i5', categoryId: 'c_mag' }, { itemId: 'i6', categoryId: 'c_nmag' }], prompt: 'Sort each object into the group that matches how it behaves with a magnet.', explanation: 'Steel spoons, paper clips and refrigerator doors are attracted to magnets, while aluminium, copper and plastic are not.', objective: 'Classify materials as magnetic or non-magnetic.', topic: 'physics', subtopic: 'electricity-magnetism', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Iron and steel are strongly attracted to magnets.' }], ...S }),
  sorting({ items: [{ id: 'i1', label: 'Tastes sour' }, { id: 'i2', label: 'Feels slippery' }, { id: 'i3', label: 'Turns blue litmus red' }, { id: 'i4', label: 'Turns red litmus blue' }, { id: 'i5', label: 'Bitter taste' }, { id: 'i6', label: 'Reacts with carbonate to make gas' }], categories: [{ id: 'c_a', label: 'Acid' }, { id: 'c_b', label: 'Base' }], assignments: [{ itemId: 'i1', categoryId: 'c_a' }, { itemId: 'i2', categoryId: 'c_b' }, { itemId: 'i3', categoryId: 'c_a' }, { itemId: 'i4', categoryId: 'c_b' }, { itemId: 'i5', categoryId: 'c_b' }, { itemId: 'i6', categoryId: 'c_a' }], prompt: 'Place each property into the acid or base group.', explanation: 'Sour taste, blue litmus turning red and carbonate reactions describe acids, while slippery feel, red litmus turning blue and bitter taste describe bases.', objective: 'Classify properties of acids and bases.', topic: 'chemistry', subtopic: 'acids-bases', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Acids taste sour and turn blue litmus red.' }], ...S }),
  sorting({ items: [{ id: 'i1', label: 'Oxygen' }, { id: 'i2', label: 'Table salt' }, { id: 'i3', label: 'Helium' }, { id: 'i4', label: 'Sugar' }, { id: 'i5', label: 'Iron' }, { id: 'i6', label: 'Water' }], categories: [{ id: 'c_el', label: 'Element' }, { id: 'c_co', label: 'Compound' }], assignments: [{ itemId: 'i1', categoryId: 'c_el' }, { itemId: 'i2', categoryId: 'c_co' }, { itemId: 'i3', categoryId: 'c_el' }, { itemId: 'i4', categoryId: 'c_co' }, { itemId: 'i5', categoryId: 'c_el' }, { itemId: 'i6', categoryId: 'c_co' }], prompt: 'Sort each substance as an element or a compound.', explanation: 'Oxygen, helium and iron are elements, while table salt, sugar and water are compounds.', objective: 'Classify substances as elements or compounds.', topic: 'chemistry', subtopic: 'elements-compounds', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'A compound is made of two or more elements joined together.' }], ...S }),
  sorting({ items: [{ id: 'i1', label: 'Cow' }, { id: 'i2', label: 'Lion' }, { id: 'i3', label: 'Bear' }, { id: 'i4', label: 'Rabbit' }, { id: 'i5', label: 'Eagle' }, { id: 'i6', label: 'Pig' }], categories: [{ id: 'c_h', label: 'Herbivore' }, { id: 'c_c', label: 'Carnivore' }, { id: 'c_o', label: 'Omnivore' }], assignments: [{ itemId: 'i1', categoryId: 'c_h' }, { itemId: 'i2', categoryId: 'c_c' }, { itemId: 'i3', categoryId: 'c_o' }, { itemId: 'i4', categoryId: 'c_h' }, { itemId: 'i5', categoryId: 'c_c' }, { itemId: 'i6', categoryId: 'c_o' }], prompt: 'Sort each animal by the type of food it eats.', explanation: 'Cows and rabbits eat plants, lions and eagles eat meat, and bears and pigs eat both plants and animals.', objective: 'Classify animals by diet.', topic: 'life', subtopic: 'plants-animals', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Herbivores eat plants, carnivores eat meat, omnivores eat both.' }], ...S }),
  sorting({ items: [{ id: 'i1', label: 'Heart' }, { id: 'i2', label: 'Stomach' }, { id: 'i3', label: 'Brain' }, { id: 'i4', label: 'Lungs' }], categories: [{ id: 'c_circ', label: 'Circulatory' }, { id: 'c_dig', label: 'Digestive' }, { id: 'c_nerv', label: 'Nervous' }, { id: 'c_resp', label: 'Respiratory' }], assignments: [{ itemId: 'i1', categoryId: 'c_circ' }, { itemId: 'i2', categoryId: 'c_dig' }, { itemId: 'i3', categoryId: 'c_nerv' }, { itemId: 'i4', categoryId: 'c_resp' }], prompt: 'Place each organ into the body system it belongs to.', explanation: 'The heart pumps blood in the circulatory system, the stomach digests food, the brain controls the nervous system and the lungs exchange gases.', objective: 'Match organs to their body systems.', topic: 'life', subtopic: 'body-systems', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think about the main job each organ does.' }], ...S }),
  sorting({ items: [{ id: 'i1', label: 'Brown eyes' }, { id: 'i2', label: 'Blue eyes' }, { id: 'i3', label: 'Attached earlobes' }, { id: 'i4', label: 'Free earlobes' }, { id: 'i5', label: 'Dimples' }, { id: 'i6', label: 'Straight hairline' }], categories: [{ id: 'c_d', label: 'Dominant trait' }, { id: 'c_r', label: 'Recessive trait' }], assignments: [{ itemId: 'i1', categoryId: 'c_d' }, { itemId: 'i2', categoryId: 'c_r' }, { itemId: 'i3', categoryId: 'c_r' }, { itemId: 'i4', categoryId: 'c_d' }, { itemId: 'i5', categoryId: 'c_d' }, { itemId: 'i6', categoryId: 'c_r' }], prompt: 'Sort each trait as dominant or recessive.', explanation: 'Brown eyes, free earlobes and dimples are dominant, while blue eyes, attached earlobes and a straight hairline are recessive.', objective: 'Classify traits as dominant or recessive.', topic: 'life', subtopic: 'genetics-heredity', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'A dominant trait shows even with one copy of the gene.' }], ...S }),
  sorting({ items: [{ id: 'i1', label: 'Made of solid rock we live on' }, { id: 'i2', label: 'Mostly iron and nickel' }, { id: 'i3', label: 'Semi-molten slow-flowing rock' }, { id: 'i4', label: 'The thinnest layer' }, { id: 'i5', label: 'The thickest layer' }, { id: 'i6', label: 'The hottest layer' }], categories: [{ id: 'c_cr', label: 'Crust' }, { id: 'c_ma', label: 'Mantle' }, { id: 'c_co', label: 'Core' }], assignments: [{ itemId: 'i1', categoryId: 'c_cr' }, { itemId: 'i2', categoryId: 'c_co' }, { itemId: 'i3', categoryId: 'c_ma' }, { itemId: 'i4', categoryId: 'c_cr' }, { itemId: 'i5', categoryId: 'c_ma' }, { itemId: 'i6', categoryId: 'c_co' }], prompt: 'Sort each description into the Earth layer it describes.', explanation: 'The crust is the thin rocky outer layer, the mantle is thick flowing rock, and the core is mostly iron and nickel.', objective: 'Match descriptions to the Earth layers.', topic: 'earth-space', subtopic: 'earth-structure', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'The crust is the layer under your feet.' }], ...S }),
  sorting({ items: [{ id: 'i1', label: 'Metre' }, { id: 'i2', label: 'Kilogram' }, { id: 'i3', label: 'Litre' }, { id: 'i4', label: 'Centimetre' }, { id: 'i5', label: 'Gram' }, { id: 'i6', label: 'Millilitre' }], categories: [{ id: 'c_len', label: 'Length' }, { id: 'c_mas', label: 'Mass' }, { id: 'c_vol', label: 'Volume' }], assignments: [{ itemId: 'i1', categoryId: 'c_len' }, { itemId: 'i2', categoryId: 'c_mas' }, { itemId: 'i3', categoryId: 'c_vol' }, { itemId: 'i4', categoryId: 'c_len' }, { itemId: 'i5', categoryId: 'c_mas' }, { itemId: 'i6', categoryId: 'c_vol' }], prompt: 'Sort each unit into the quantity it measures.', explanation: 'Metres and centimetres measure length, kilograms and grams measure mass, and litres and millilitres measure volume.', objective: 'Classify metric units by what they measure.', topic: 'inquiry', subtopic: 'measurement-units', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Length is how long, mass is how heavy, volume is how much space.' }], ...S }),

  matching({ leftItems: [{ id: 'l1', text: 'Wavelength' }, { id: 'l2', text: 'Frequency' }, { id: 'l3', text: 'Amplitude' }, { id: 'l4', text: 'Speed' }], rightItems: [{ id: 'r1', text: 'Distance between crests' }, { id: 'r2', text: 'Waves passing per second' }, { id: 'r3', text: 'Height of a wave' }, { id: 'r4', text: 'Distance travelled per second' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each wave term to its meaning.', explanation: 'Wavelength is the distance between crests, frequency is waves per second, amplitude is wave height and speed is distance per second.', objective: 'Match wave terms to their definitions.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Picture a water wave and describe each feature.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Kinetic energy' }, { id: 'l2', text: 'Potential energy' }, { id: 'l3', text: 'Thermal energy' }, { id: 'l4', text: 'Sound energy' }], rightItems: [{ id: 'r1', text: 'Energy of a moving ball' }, { id: 'r2', text: 'Stored energy in a raised weight' }, { id: 'r3', text: 'Heat from a kettle' }, { id: 'r4', text: 'Energy of a plucked string' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each energy type to its example.', explanation: 'A moving ball has kinetic energy, a raised weight stores potential energy, a kettle gives thermal energy and a plucked string makes sound energy.', objective: 'Match energy types to examples.', topic: 'physics', subtopic: 'energy', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think of movement, stored position, heat and vibration.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Colour change' }, { id: 'l2', text: 'Gas bubbles' }, { id: 'l3', text: 'Temperature rise' }, { id: 'l4', text: 'Solid forms in a liquid' }], rightItems: [{ id: 'r1', text: 'May mean a new substance formed' }, { id: 'r2', text: 'Gas is being released' }, { id: 'r3', text: 'Energy is being given out' }, { id: 'r4', text: 'A precipitate has formed' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each observation to the change it suggests.', explanation: 'A colour change can signal a new substance, bubbles show gas released, a temperature rise shows energy out, and a solid in a liquid is a precipitate.', objective: 'Match reaction observations to their meanings.', topic: 'chemistry', subtopic: 'reactions-changes', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Connect each clue to what it tells you about the reaction.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Na' }, { id: 'l2', text: 'Cl' }, { id: 'l3', text: 'Fe' }, { id: 'l4', text: 'Au' }], rightItems: [{ id: 'r1', text: 'Sodium' }, { id: 'r2', text: 'Chlorine' }, { id: 'r3', text: 'Iron' }, { id: 'r4', text: 'Gold' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each element symbol to its name.', explanation: 'Na is sodium, Cl is chlorine, Fe is iron and Au is gold.', objective: 'Match element symbols to element names.', topic: 'chemistry', subtopic: 'periodic-table', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Some symbols come from Latin names.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Chloroplast' }, { id: 'l2', text: 'Cell wall' }, { id: 'l3', text: 'Vacuole' }, { id: 'l4', text: 'Ribosome' }], rightItems: [{ id: 'r1', text: 'Carries out photosynthesis' }, { id: 'r2', text: 'Supports a plant cell' }, { id: 'r3', text: 'Stores water and other substances' }, { id: 'r4', text: 'Makes proteins' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each cell part to the job it does.', explanation: 'Chloroplasts carry out photosynthesis, the cell wall supports the plant cell, vacuoles store water and ribosomes build proteins.', objective: 'Match cell parts to their functions.', topic: 'life', subtopic: 'cells-organisms', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Green parts trap sunlight; the wall gives the cell shape.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Cactus' }, { id: 'l2', text: 'Camel' }, { id: 'l3', text: 'Penguin' }, { id: 'l4', text: 'Shark' }], rightItems: [{ id: 'r1', text: 'Stores water in its stem' }, { id: 'r2', text: 'Survives long without water' }, { id: 'r3', text: 'Thick feathers trap heat' }, { id: 'r4', text: 'Streamlined body for fast swimming' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each living thing to its adaptation.', explanation: 'A cactus stores water, a camel survives long without water, a penguin traps heat with feathers and a shark is streamlined for swimming.', objective: 'Match adaptations to organisms.', topic: 'life', subtopic: 'evolution-ecosystems', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think about the habitat each one lives in.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Muscular system' }, { id: 'l2', text: 'Endocrine system' }, { id: 'l3', text: 'Immune system' }, { id: 'l4', text: 'Excretory system' }], rightItems: [{ id: 'r1', text: 'Causes movement' }, { id: 'r2', text: 'Releases hormones' }, { id: 'r3', text: 'Fights infection' }, { id: 'r4', text: 'Removes waste' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each body system to its main role.', explanation: 'The muscular system moves the body, the endocrine system releases hormones, the immune system fights infection and the excretory system removes waste.', objective: 'Match body systems to their roles.', topic: 'life', subtopic: 'body-systems', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Focus on the one main job of each system.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Mercury' }, { id: 'l2', text: 'Saturn' }, { id: 'l3', text: 'Mars' }, { id: 'l4', text: 'Jupiter' }], rightItems: [{ id: 'r1', text: 'The smallest planet' }, { id: 'r2', text: 'Has the most visible rings' }, { id: 'r3', text: 'Called the Red Planet' }, { id: 'r4', text: 'The largest planet' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each planet to its key feature.', explanation: 'Mercury is the smallest, Saturn has visible rings, Mars is the Red Planet and Jupiter is the largest.', objective: 'Match planets to their features.', topic: 'earth-space', subtopic: 'solar-system', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Remember the largest and smallest planets first.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Thermometer' }, { id: 'l2', text: 'Barometer' }, { id: 'l3', text: 'Anemometer' }, { id: 'l4', text: 'Rain gauge' }], rightItems: [{ id: 'r1', text: 'Measures temperature' }, { id: 'r2', text: 'Measures air pressure' }, { id: 'r3', text: 'Measures wind speed' }, { id: 'r4', text: 'Measures rainfall' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each weather instrument to what it measures.', explanation: 'A thermometer reads temperature, a barometer reads air pressure, an anemometer reads wind speed and a rain gauge collects rainfall.', objective: 'Match weather instruments to their measurements.', topic: 'earth-space', subtopic: 'weather-climate', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Connect each tool name to the weather factor it tracks.' }], ...S }),

  ordering({ items: [{ id: 'o1', label: 'Chemical energy in coal' }, { id: 'o2', label: 'Thermal energy of steam' }, { id: 'o3', label: 'Kinetic energy of the turbine' }, { id: 'o4', label: 'Electrical energy from the generator' }], order: ['o1', 'o2', 'o3', 'o4'], prompt: 'Arrange the energy changes in a coal power station in order.', explanation: 'Burning coal releases chemical energy as heat, the heat turns water to steam, the steam spins the turbine and the generator makes electricity.', objective: 'Order energy transformations in a power station.', topic: 'physics', subtopic: 'energy', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Follow the chain: fuel to heat to motion to electricity.' }], ...S }),
  ordering({ items: [{ id: 'o1', label: 'Red' }, { id: 'o2', label: 'Orange' }, { id: 'o3', label: 'Yellow' }, { id: 'o4', label: 'Green' }, { id: 'o5', label: 'Blue' }, { id: 'o6', label: 'Violet' }], order: ['o1', 'o2', 'o3', 'o4', 'o5', 'o6'], prompt: 'Order the colours of the rainbow from the longest wavelength to the shortest.', explanation: 'Red has the longest wavelength and violet the shortest, so the order is red, orange, yellow, green, blue, violet.', objective: 'Order rainbow colours by wavelength.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Red comes first; violet comes last.' }], ...S }),
  ordering({ items: [{ id: 'o1', label: 'Ice particles gain energy' }, { id: 'o2', label: 'Particles vibrate more quickly' }, { id: 'o3', label: 'Particles break free of fixed positions' }, { id: 'o4', label: 'Particles slide past one another' }], order: ['o1', 'o2', 'o3', 'o4'], prompt: 'Put the steps of ice melting in order at the particle level.', explanation: 'As ice warms, particles gain energy, vibrate faster, break free of fixed positions and then slide past one another as a liquid.', objective: 'Order the particle changes during melting.', topic: 'chemistry', subtopic: 'matter-particles', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Energy comes first, then movement increases.' }], ...S }),
  ordering({ items: [{ id: 'o1', label: 'Cell' }, { id: 'o2', label: 'Tissue' }, { id: 'o3', label: 'Organ' }, { id: 'o4', label: 'Organ system' }, { id: 'o5', label: 'Organism' }], order: ['o1', 'o2', 'o3', 'o4', 'o5'], prompt: 'Order the levels of organisation in a living thing from smallest to largest.', explanation: 'Cells form tissues, tissues form organs, organs form organ systems and systems form the organism.', objective: 'Order biological organisation levels.', topic: 'life', subtopic: 'cells-organisms', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Cells are the smallest unit; the organism is the whole body.' }], ...S }),
  ordering({ items: [{ id: 'o1', label: 'New moon' }, { id: 'o2', label: 'Crescent moon' }, { id: 'o3', label: 'Half moon' }, { id: 'o4', label: 'Gibbous moon' }, { id: 'o5', label: 'Full moon' }], order: ['o1', 'o2', 'o3', 'o4', 'o5'], prompt: 'Order the Moon phases from new moon to full moon.', explanation: 'From the new moon the lit part grows through crescent, half, gibbous and finally a full moon.', objective: 'Order the Moon phases as the lit part grows.', topic: 'earth-space', subtopic: 'solar-system', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Start dark and finish fully lit.' }], ...S }),
  ordering({ items: [{ id: 'o1', label: 'Mercury' }, { id: 'o2', label: 'Venus' }, { id: 'o3', label: 'Earth' }, { id: 'o4', label: 'Mars' }, { id: 'o5', label: 'Jupiter' }, { id: 'o6', label: 'Saturn' }], order: ['o1', 'o2', 'o3', 'o4', 'o5', 'o6'], prompt: 'Order the planets from the Sun outward.', explanation: 'From the Sun the planets are Mercury, Venus, Earth, Mars, Jupiter and Saturn.', objective: 'Order the first six planets by distance from the Sun.', topic: 'earth-space', subtopic: 'solar-system', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'My Very Educated Mother Just Said... gives the planet order.' }], ...S }),
  ordering({ items: [{ id: 'o1', label: 'Weathering breaks rock apart' }, { id: 'o2', label: 'Erosion carries pieces away' }, { id: 'o3', label: 'Sediment is deposited' }, { id: 'o4', label: 'Layers are compacted' }, { id: 'o5', label: 'Particles cement together' }], order: ['o1', 'o2', 'o3', 'o4', 'o5'], prompt: 'Order the steps that form sedimentary rock.', explanation: 'Rock weathers into pieces, erosion carries them away, sediment is deposited, layers compact and finally cement into rock.', objective: 'Order the formation of sedimentary rock.', topic: 'earth-space', subtopic: 'rock-cycle', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Start with breaking rock apart; end with hardening.' }], ...S }),
  ordering({ items: [{ id: 'o1', label: 'Choose the variable to change' }, { id: 'o2', label: 'Identify the variables to keep the same' }, { id: 'o3', label: 'Decide what to measure' }, { id: 'o4', label: 'Run the test and record results' }], order: ['o1', 'o2', 'o3', 'o4'], prompt: 'Order the steps for planning a fair test.', explanation: 'First choose the independent variable, then decide what to keep constant, decide what to measure and finally run the test.', objective: 'Order the steps of a fair experiment.', topic: 'inquiry', subtopic: 'scientific-method', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Only change one thing at a time.' }], ...S }),
  ordering({ items: [{ id: 'o1', label: 'Gene' }, { id: 'o2', label: 'Chromosome' }, { id: 'o3', label: 'Nucleus' }, { id: 'o4', label: 'Cell' }], order: ['o1', 'o2', 'o3', 'o4'], prompt: 'Order these genetic structures from smallest to largest.', explanation: 'A gene is a section of DNA inside a chromosome, chromosomes sit in the nucleus and the nucleus lies within the cell.', objective: 'Order genetic structures by size.', topic: 'life', subtopic: 'genetics-heredity', difficulty: 4, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Genes are pieces of DNA; the cell is the largest unit here.' }], ...S }),

  fillComplete({ template: 'A material that lets electric current flow through it easily is called a ___.', blanks: [{ id: 'b1', type: 'text', label: 'material', maxLength: 12 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['conductor'] }], prompt: 'A material that lets electric current flow through it easily is called a ___.', explanation: 'Conductors such as copper allow electric current to flow through them easily.', objective: 'Name a material that conducts electricity.', topic: 'physics', subtopic: 'electricity-magnetism', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Copper wire is a good example.' }], ...S }),
  fillComplete({ template: 'The unit used to measure force is the ___.', blanks: [{ id: 'b1', type: 'text', label: 'unit', maxLength: 10 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['newton'] }], prompt: 'The unit used to measure force is the ___.', explanation: 'Force is measured in newtons, named after the scientist Isaac Newton.', objective: 'Name the unit of force.', topic: 'physics', subtopic: 'forces-motion', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is named after a famous scientist.' }], ...S }),
  fillComplete({ template: 'The energy stored in a stretched rubber band is called ___ energy.', blanks: [{ id: 'b1', type: 'text', label: 'energy type', maxLength: 12 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['potential'] }], prompt: 'The energy stored in a stretched rubber band is called ___ energy.', explanation: 'A stretched rubber band stores potential energy that can be released as motion.', objective: 'Name the stored energy in a stretched object.', topic: 'physics', subtopic: 'energy', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Stored energy is potential energy.' }], ...S }),
  fillComplete({ template: 'A solution with a pH below 7 is called an ___.', blanks: [{ id: 'b1', type: 'text', label: 'substance', maxLength: 8 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['acid'] }], prompt: 'A solution with a pH below 7 is called an ___.', explanation: 'Solutions with a pH below 7 are acidic, such as lemon juice and vinegar.', objective: 'Name a solution with a pH below 7.', topic: 'chemistry', subtopic: 'acids-bases', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think about which substances have a low pH.' }], ...S }),
  fillComplete({ template: 'The organ that pumps blood around the body is the ___.', blanks: [{ id: 'b1', type: 'text', label: 'organ', maxLength: 8 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['heart'] }], prompt: 'The organ that pumps blood around the body is the ___.', explanation: 'The heart pumps blood through the circulatory system to the whole body.', objective: 'Name the organ that pumps blood.', topic: 'life', subtopic: 'body-systems', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It beats about 70 times a minute.' }], ...S }),
  fillComplete({ template: 'Plants make their own food using sunlight through the process of ___.', blanks: [{ id: 'b1', type: 'text', label: 'process', maxLength: 16 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['photosynthesis'] }], prompt: 'Plants make their own food using sunlight through the process of ___.', explanation: 'Photosynthesis uses sunlight, water and carbon dioxide to make food for the plant.', objective: 'Name the food-making process in plants.', topic: 'life', subtopic: 'plants-animals', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It happens in the green leaves.' }], ...S }),
  fillComplete({ template: 'A feature that helps an organism survive in its habitat is called a(n) ___.', blanks: [{ id: 'b1', type: 'text', label: 'feature', maxLength: 14 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['adaptation'] }], prompt: 'A feature that helps an organism survive in its habitat is called a(n) ___.', explanation: 'An adaptation is a body part or behaviour that helps an organism survive in its environment.', objective: 'Name a feature that helps survival.', topic: 'life', subtopic: 'evolution-ecosystems', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Camels have adaptations for the desert.' }], ...S }),
  fillComplete({ template: 'The hot, slowly flowing rock layer found below the crust is called the ___.', blanks: [{ id: 'b1', type: 'text', label: 'layer', maxLength: 10 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['mantle'] }], prompt: 'The hot, slowly flowing rock layer found below the crust is called the ___.', explanation: 'The mantle lies beneath the crust and is made of hot, slowly flowing rock.', objective: 'Name the layer below the crust.', topic: 'earth-space', subtopic: 'earth-structure', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is the thickest layer of the Earth.' }], ...S }),
  fillComplete({ template: 'The average weather of a place over many years is called its ___.', blanks: [{ id: 'b1', type: 'text', label: 'weather pattern', maxLength: 10 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['climate'] }], prompt: 'The average weather of a place over many years is called its ___.', explanation: 'Climate describes long-term weather patterns, while weather is day-to-day.', objective: 'Name the long-term weather pattern of a place.', topic: 'earth-space', subtopic: 'weather-climate', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Weather is today; this is over decades.' }], ...S }),
  fillComplete({ template: 'A resource that nature can replace as fast as we use it is described as ___.', blanks: [{ id: 'b1', type: 'text', label: 'resource type', maxLength: 12 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['renewable'] }], prompt: 'A resource that nature can replace as fast as we use it is described as ___.', explanation: 'Renewable resources like sunlight and wind are replaced naturally within a short time.', objective: 'Name resources that nature replaces.', topic: 'earth-space', subtopic: 'natural-resources', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Solar and wind energy are examples.' }], ...S }),
  fillComplete({ template: 'A gas collected in a reaction fills 250 cm³. Write this volume in litres. ___ L', blanks: [{ id: 'b1', type: 'number', label: 'volume in litres', maxLength: 10 }], numeric: [{ blankId: 'b1', value: 0.25, tolerance: 0.005 }], prompt: 'A gas collected in a reaction fills 250 cm³. Write this volume in litres. ___ L', explanation: '1000 cm³ equals 1 litre, so 250 cm³ is 0.25 L.', objective: 'Convert cubic centimetres to litres.', topic: 'inquiry', subtopic: 'measurement-units', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Divide by 1000 to change cm³ to litres.' }], ...S }),
  fillComplete({ template: 'On a line graph, the variable you change on purpose is placed on the x-axis and is called the ___ variable.', blanks: [{ id: 'b1', type: 'text', label: 'variable', maxLength: 14 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['independent'] }], prompt: 'On a line graph, the variable you change on purpose is placed on the x-axis and is called the ___ variable.', explanation: 'The independent variable is the one you change, and it is plotted on the x-axis.', objective: 'Name the variable on the x-axis.', topic: 'inquiry', subtopic: 'data-graphing', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is the variable you control in the experiment.' }], ...S }),

  imageInteraction({ image: { ref: 'question-media/science/physics/circuit-battery.png', alt: 'Simple circuit diagram with a battery, bulb and connecting wires.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'The battery', x: 50, y: 30, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The diagram shows a simple circuit. Tap the part that supplies the energy.', explanation: 'The battery supplies the electrical energy that pushes the current around the circuit.', objective: 'Identify the battery in a circuit diagram.', topic: 'physics', subtopic: 'electricity-magnetism', difficulty: 4, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It has a plus and a minus sign.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/physics/car-forces.png', alt: 'Side view of a car with arrows showing thrust, friction, gravity and support.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Friction', x: 30, y: 80, radius: 12 }, { id: 'h2', label: 'Gravity', x: 50, y: 95, radius: 10 }, { id: 'h3', label: 'Support', x: 50, y: 5, radius: 10 }, { id: 'h4', label: 'Thrust', x: 70, y: 20, radius: 10 }], requiredHotspots: ['h1'], prompt: 'The arrows show the forces acting on a moving car. Tap the force that slows the car down.', explanation: 'Friction between the tyres and the road opposes motion and slows the car.', objective: 'Identify the frictional force on a car.', topic: 'physics', subtopic: 'forces-motion', difficulty: 4, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It acts between the tyres and the road.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/physics/wave-diagram.png', alt: 'Transverse wave with labelled crest, trough and wavelength arrows.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Wavelength', x: 50, y: 15, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The wave diagram shows the distance between two crests. Tap the arrow that marks the wavelength.', explanation: 'The wavelength is the distance between two consecutive crests of the wave.', objective: 'Identify the wavelength on a wave diagram.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Measure from one crest to the next crest.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/chemistry/particle-states.png', alt: 'Three boxes showing particles packed tightly, touching loosely, and far apart.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Solid particles', x: 20, y: 50, radius: 12 }, { id: 'h2', label: 'Liquid particles', x: 50, y: 50, radius: 12 }, { id: 'h3', label: 'Gas particles', x: 80, y: 50, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The boxes show particles in different states. Tap the box where particles are packed most tightly.', explanation: 'In a solid, particles are packed closely together in fixed positions.', objective: 'Identify the particle arrangement of a solid.', topic: 'chemistry', subtopic: 'matter-particles', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'The tightest packing is a solid.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/chemistry/periodic-table.png', alt: 'Periodic table with element groups coloured.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Noble gases', x: 90, y: 15, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The periodic table shows the groups of elements. Tap the column that holds the noble gases.', explanation: 'The noble gases such as helium, neon and argon sit in the column on the far right of the table.', objective: 'Locate the noble gases on the periodic table.', topic: 'chemistry', subtopic: 'periodic-table', difficulty: 4, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'They are on the far right and rarely react.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/chemistry/reacting-test-tube.png', alt: 'Test tube over a beaker with gas bubbles rising from a liquid.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Gas bubbles', x: 50, y: 25, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The test tube shows a reaction. Tap the part where gas is being produced.', explanation: 'The bubbles rising through the liquid show that a gas is being released during the reaction.', objective: 'Identify gas production in a reaction.', topic: 'chemistry', subtopic: 'reactions-changes', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Look for the rising bubbles.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/life/plant-cell.png', alt: 'Plant cell diagram with wall, membrane, nucleus, chloroplasts and vacuole.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Chloroplast', x: 65, y: 30, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The diagram shows a plant cell. Tap the part that carries out photosynthesis.', explanation: 'Chloroplasts contain chlorophyll and carry out photosynthesis.', objective: 'Identify the chloroplast in a plant cell.', topic: 'life', subtopic: 'cells-organisms', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is the green part.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/life/lungs-diagram.png', alt: 'Diagram of the human respiratory system showing the lungs and airways.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Lungs', x: 50, y: 40, radius: 14 }], requiredHotspots: ['h1'], prompt: 'Look at the respiratory system diagram. Tap the organs that exchange gases with the air.', explanation: 'The lungs exchange oxygen and carbon dioxide between the air and the blood.', objective: 'Identify the lungs in the respiratory system.', topic: 'life', subtopic: 'body-systems', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'You breathe with these two organs.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/life/flower-structure.png', alt: 'Flower diagram showing petals, stamen and stigma.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Stamen', x: 50, y: 25, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The flower diagram shows its parts. Tap the part that produces pollen.', explanation: 'The stamen produces pollen, which is needed for fertilisation.', objective: 'Identify the pollen-producing part of a flower.', topic: 'life', subtopic: 'plants-animals', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is the male part of the flower.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/life/food-web.png', alt: 'Food web with grass, mouse, rabbit, fox and owl connected by arrows.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Grass', x: 22, y: 90, radius: 14 }], requiredHotspots: ['h1'], prompt: 'The food web shows feeding relationships. Tap the organism that makes its own food.', explanation: 'The grass is the producer because it makes its own food by photosynthesis.', objective: 'Identify the producer in a food web.', topic: 'life', subtopic: 'evolution-ecosystems', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Producers are usually green plants.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/earth-space/earth-layers.png', alt: 'Cross-section of the Earth with the inner core at the centre.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Inner core', x: 50, y: 50, radius: 10 }], requiredHotspots: ['h1'], prompt: 'This Earth cross-section shows the layers. Tap the hottest layer at the centre.', explanation: 'The inner core is at the centre of the Earth and is the hottest layer.', objective: 'Identify the inner core in the Earth diagram.', topic: 'earth-space', subtopic: 'earth-structure', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is right in the middle.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/earth-space/solar-system.png', alt: 'The planets arranged in order from the Sun.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Mercury', x: 10, y: 50, radius: 12 }], requiredHotspots: ['h1'], prompt: 'Planets are drawn in order from the Sun. Tap the planet closest to the Sun.', explanation: 'Mercury is the closest planet to the Sun, followed by Venus and Earth.', objective: 'Identify the planet closest to the Sun.', topic: 'earth-space', subtopic: 'solar-system', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It is the first planet from the Sun.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/earth-space/water-cycle.png', alt: 'Water cycle diagram showing evaporation, condensation and precipitation.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Condensation', x: 50, y: 15, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The water cycle diagram shows its stages. Tap the stage where water vapour cools to form clouds.', explanation: 'Condensation is the stage where water vapour cools and forms clouds.', objective: 'Identify condensation in the water cycle.', topic: 'earth-space', subtopic: 'weather-climate', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'It happens high up where the air is cool.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/inquiry/lab-safety-gear.png', alt: 'Lab bench with safety goggles, gloves, apron and a flame.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'tap', hotspots: [{ id: 'h1', label: 'Goggles', x: 20, y: 30, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The picture shows safety equipment in a lab. Tap the item that protects your eyes.', explanation: 'Safety goggles protect the eyes from splashes and flying particles.', objective: 'Identify the eye protection item.', topic: 'inquiry', subtopic: 'lab-safety', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'You wear it over your eyes.' }], ...S }),

  pattern({ sequence: [{ id: 'e1', text: '10 Hz' }, { id: 'e2', text: '20 Hz' }, { id: 'e3', text: '30 Hz' }], interaction: 'complete-sequence', candidates: [{ id: 'c1', text: '40 Hz' }, { id: 'c2', text: '35 Hz' }, { id: 'c3', text: '50 Hz' }, { id: 'c4', text: '60 Hz' }], answer: { type: 'candidate', rule: 'Each wave vibrates 10 more times per second than the last.', acceptableIds: ['c1'] }, prompt: 'Choose the next frequency: 10 Hz, 20 Hz, 30 Hz, …', explanation: 'The pattern adds 10 Hz each time, so the next frequency is 40 Hz.', objective: 'Extend a pattern of increasing frequencies.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Add 10 to the last number.' }], ...S }),
  pattern({ sequence: [{ id: 'e1', text: 'Lithium (3)' }, { id: 'e2', text: 'Beryllium (4)' }, { id: 'e3', text: 'Boron (5)' }], interaction: 'complete-sequence', candidates: [{ id: 'c1', text: 'Carbon (6)' }, { id: 'c2', text: 'Nitrogen (7)' }, { id: 'c3', text: 'Aluminium (13)' }, { id: 'c4', text: 'Beryllium (4)' }], answer: { type: 'candidate', rule: 'The atomic numbers rise by one across the row.', acceptableIds: ['c1'] }, prompt: 'Choose the next element: Lithium (3), Beryllium (4), Boron (5), …', explanation: 'Each element in the row has an atomic number one higher, so carbon (6) follows boron.', objective: 'Extend a pattern of element atomic numbers.', topic: 'chemistry', subtopic: 'periodic-table', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Add 1 to the last atomic number.' }], ...S }),
  pattern({ sequence: [{ id: 'e1', text: 'Mercury' }, { id: 'e2', text: 'Venus' }, { id: 'e3', text: 'Earth' }], interaction: 'complete-sequence', candidates: [{ id: 'c1', text: 'Mars' }, { id: 'c2', text: 'Jupiter' }, { id: 'c3', text: 'Neptune' }, { id: 'c4', text: 'Moon' }], answer: { type: 'candidate', rule: 'Planets listed in order of distance from the Sun.', acceptableIds: ['c1'] }, prompt: 'Choose the next planet: Mercury, Venus, Earth, …', explanation: 'Mars is the fourth planet from the Sun, so it follows Earth in the list.', objective: 'Extend the order of the planets from the Sun.', topic: 'earth-space', subtopic: 'solar-system', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Remember the order starting from the Sun.' }], ...S }),
  pattern({ sequence: [{ id: 'e1', text: '1.5 s' }, { id: 'e2', text: '3.0 s' }, { id: 'e3', text: '6.0 s' }], interaction: 'complete-sequence', candidates: [{ id: 'c1', text: '12.0 s' }, { id: 'c2', text: '9.0 s' }, { id: 'c3', text: '10.0 s' }, { id: 'c4', text: '18.0 s' }], answer: { type: 'candidate', rule: 'Each reading doubles the time before it.', acceptableIds: ['c1'] }, prompt: 'Choose the next reading: 1.5 s, 3.0 s, 6.0 s, …', explanation: 'Each value doubles the one before it, so the next reading is 12.0 s.', objective: 'Extend a doubling pattern of measurements.', topic: 'inquiry', subtopic: 'data-graphing', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Multiply the last value by 2.' }], ...S }),

  memory({ cards: [{ id: 'c1', text: 'Kinetic' }, { id: 'c2', text: 'Energy of motion' }, { id: 'c3', text: 'Potential' }, { id: 'c4', text: 'Stored energy' }, { id: 'c5', text: 'Thermal' }, { id: 'c6', text: 'Heat energy' }, { id: 'c7', text: 'Sound' }, { id: 'c8', text: 'Energy of vibrations' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each energy type with its description.', deckType: 'pairs', prompt: 'Match each energy type to its description from memory.', explanation: 'Kinetic energy is energy of motion, potential energy is stored, thermal is heat and sound travels as vibrations.', objective: 'Recall energy types and their descriptions.', topic: 'physics', subtopic: 'energy', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Link each type to what it comes from.' }], ...S }),
  memory({ cards: [{ id: 'c1', text: 'Transparent' }, { id: 'c2', text: 'Lets most light through' }, { id: 'c3', text: 'Opaque' }, { id: 'c4', text: 'Blocks all light' }, { id: 'c5', text: 'Reflection' }, { id: 'c6', text: 'Light bounces off' }, { id: 'c7', text: 'Refraction' }, { id: 'c8', text: 'Light bends' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each light behaviour with its meaning.', deckType: 'pairs', prompt: 'Learn what each light behaviour means, then connect the pairs.', explanation: 'Transparent materials pass most light, opaque ones block it, reflection bounces light and refraction bends it.', objective: 'Recall terms for light behaviour.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think about what happens to a light beam.' }], ...S }),
  memory({ cards: [{ id: 'c1', text: 'Reactant' }, { id: 'c2', text: 'Starting substance' }, { id: 'c3', text: 'Product' }, { id: 'c4', text: 'New substance formed' }, { id: 'c5', text: 'Catalyst' }, { id: 'c6', text: 'Speeds up the reaction' }, { id: 'c7', text: 'Exothermic' }, { id: 'c8', text: 'Releases heat' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each reaction term with its meaning.', deckType: 'pairs', prompt: 'Remember each reaction term and its meaning, then match the cards.', explanation: 'Reactants are the starting substances, products are what forms, a catalyst speeds up a reaction and exothermic reactions release heat.', objective: 'Recall terms used in chemical reactions.', topic: 'chemistry', subtopic: 'reactions-changes', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Connect each term to its part in a reaction.' }], ...S }),
  memory({ cards: [{ id: 'c1', text: 'Atom' }, { id: 'c2', text: 'Smallest particle of an element' }, { id: 'c3', text: 'Molecule' }, { id: 'c4', text: 'Two or more atoms joined' }, { id: 'c5', text: 'Element' }, { id: 'c6', text: 'One type of atom' }, { id: 'c7', text: 'Compound' }, { id: 'c8', text: 'Atoms of different elements joined' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each particle term with its meaning.', deckType: 'pairs', prompt: 'Study each particle term with its meaning, then pair them up.', explanation: 'Atoms are the smallest particles of elements, molecules join atoms, elements hold one atom type and compounds join different atoms.', objective: 'Recall terms for particles of matter.', topic: 'chemistry', subtopic: 'matter-particles', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Compare the size and make-up of each particle.' }], ...S }),
  memory({ cards: [{ id: 'c1', text: 'Producer' }, { id: 'c2', text: 'Makes its own food' }, { id: 'c3', text: 'Consumer' }, { id: 'c4', text: 'Eats other organisms' }, { id: 'c5', text: 'Herbivore' }, { id: 'c6', text: 'Eats plants' }, { id: 'c7', text: 'Predator' }, { id: 'c8', text: 'Hunts other animals' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each feeding role with its meaning.', deckType: 'pairs', prompt: 'Recall each feeding role and what it eats, then match the pairs.', explanation: 'Producers make their own food, consumers eat other organisms, herbivores eat plants and predators hunt animals.', objective: 'Recall feeding roles in an ecosystem.', topic: 'life', subtopic: 'evolution-ecosystems', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think about what each organism eats.' }], ...S }),
  memory({ cards: [{ id: 'c1', text: 'Heart' }, { id: 'c2', text: 'Pumps blood' }, { id: 'c3', text: 'Lungs' }, { id: 'c4', text: 'Exchange gases' }, { id: 'c5', text: 'Stomach' }, { id: 'c6', text: 'Digests food' }, { id: 'c7', text: 'Brain' }, { id: 'c8', text: 'Controls the body' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each organ with its job.', deckType: 'pairs', prompt: 'Learn the main job of each organ, then connect the pairs.', explanation: 'The heart pumps blood, the lungs exchange gases, the stomach digests food and the brain controls the body.', objective: 'Recall the main jobs of four organs.', topic: 'life', subtopic: 'body-systems', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Match the organ to its most obvious job.' }], ...S }),
  memory({ cards: [{ id: 'c1', text: 'Evaporation' }, { id: 'c2', text: 'Liquid to gas' }, { id: 'c3', text: 'Condensation' }, { id: 'c4', text: 'Gas to liquid' }, { id: 'c5', text: 'Precipitation' }, { id: 'c6', text: 'Rain or snow' }, { id: 'c7', text: 'Run-off' }, { id: 'c8', text: 'Water flowing over land' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each water-cycle process with its meaning.', deckType: 'pairs', prompt: 'Remember each water-cycle process, then match the pairs.', explanation: 'Evaporation turns liquid to gas, condensation turns gas to liquid, precipitation is rain or snow and run-off is water flowing over land.', objective: 'Recall water-cycle processes.', topic: 'earth-space', subtopic: 'weather-climate', difficulty: 2, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Think about the direction each change goes.' }], ...S }),
  memory({ cards: [{ id: 'c1', text: 'Crust' }, { id: 'c2', text: 'Thin outer layer' }, { id: 'c3', text: 'Mantle' }, { id: 'c4', text: 'Hot flowing rock' }, { id: 'c5', text: 'Outer core' }, { id: 'c6', text: 'Liquid metal' }, { id: 'c7', text: 'Inner core' }, { id: 'c8', text: 'Solid metal' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each Earth layer with its feature.', deckType: 'pairs', prompt: 'Study each Earth layer with its feature, then pair the cards.', explanation: 'The crust is the thin outer layer, the mantle is hot flowing rock, the outer core is liquid metal and the inner core is solid metal.', objective: 'Recall features of the Earth layers.', topic: 'earth-space', subtopic: 'earth-structure', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Work from the outside in.' }], ...S }),
  memory({ cards: [{ id: 'c1', text: 'Goggles' }, { id: 'c2', text: 'Protect the eyes' }, { id: 'c3', text: 'Gloves' }, { id: 'c4', text: 'Protect the hands' }, { id: 'c5', text: 'Apron' }, { id: 'c6', text: 'Protect clothing' }, { id: 'c7', text: 'Fume hood' }, { id: 'c8', text: 'Removes harmful vapours' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each safety item with its purpose.', deckType: 'pairs', prompt: 'Match each safety item to its purpose from memory.', explanation: 'Goggles protect the eyes, gloves protect the hands, an apron protects clothing and a fume hood removes harmful vapours.', objective: 'Recall lab safety equipment and their uses.', topic: 'inquiry', subtopic: 'lab-safety', difficulty: 1, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Match each item to the part it protects.' }], ...S }),

  scenario({
    scenarioText: 'Your group sets up a circuit with a bulb and wires, but when you close the switch the bulb stays dark.',
    entryDecision: 'd1',
    decisions: [
      { id: 'd1', text: 'What should you check first?', options: [
        { id: 'opt_connections', text: 'Check that the wires are connected to the bulb and battery', nextDecision: null, outcomeText: 'The bulb lights once the loose wire is reconnected — a good first step.' },
        { id: 'opt_battery', text: 'Replace the battery straight away', nextDecision: null, outcomeText: 'You used a fresh part without checking; the loose wire was the real problem.' },
        { id: 'opt_touch', text: 'Touch the wires together with bare hands', nextDecision: null, outcomeText: 'Touching live wires can cause a shock and is unsafe.' },
      ] },
    ],
    optimalPath: [{ decisionId: 'd1', optionId: 'opt_connections' }],
    prompt: 'Choose the best first step to fix a broken circuit.',
    explanation: 'Checking the connections is the safe, logical first step because loose wires are the most common cause.',
    objective: 'Apply problem-solving to a faulty circuit.',
    topic: 'physics', subtopic: 'electricity-magnetism', difficulty: 2, gradeMin: 7, gradeMax: 9,
    hints: [{ level: 1, text: 'Look for loose wires before changing parts.' }], ...S,
  }),
  scenario({
    scenarioText: 'You are asked to identify an unknown white powder using a safe test.',
    entryDecision: 'd1',
    decisions: [
      { id: 'd1', text: 'How should you begin?', options: [
        { id: 'opt_procedure', text: 'Follow the written test procedure step by step', nextDecision: null, outcomeText: 'Following the procedure gives reliable results safely — the correct approach.' },
        { id: 'opt_taste', text: 'Taste a little to see if it is sugar', nextDecision: null, outcomeText: 'Never taste chemicals; it could be harmful.' },
        { id: 'opt_mix', text: 'Mix it with every liquid you can find', nextDecision: null, outcomeText: 'Mixing unknown chemicals can cause dangerous reactions.' },
      ] },
    ],
    optimalPath: [{ decisionId: 'd1', optionId: 'opt_procedure' }],
    prompt: 'Choose the safest way to identify an unknown powder.',
    explanation: 'A written, supervised test procedure is the safe way to identify an unknown substance.',
    objective: 'Apply safe identification steps in the lab.',
    topic: 'chemistry', subtopic: 'reactions-changes', difficulty: 2, gradeMin: 7, gradeMax: 9,
    hints: [{ level: 1, text: 'Never taste or randomly mix chemicals.' }], ...S,
  }),
  scenario({
    scenarioText: 'A classroom plant looks wilted even though it is in bright light near a window.',
    entryDecision: 'd1',
    decisions: [
      { id: 'd1', text: 'What should you do to help the plant?', options: [
        { id: 'opt_water', text: 'Check the soil moisture and water it if dry, then record what you do', nextDecision: null, outcomeText: 'Watering when dry revives the plant and your record helps others — the best choice.' },
        { id: 'opt_soda', text: 'Pour fizzy drink into the soil for extra energy', nextDecision: null, outcomeText: 'Fizzy drinks can harm roots and do not feed plants properly.' },
        { id: 'opt_more', text: 'Move it into direct hot sun all day', nextDecision: null, outcomeText: 'Very strong sunlight can scorch the leaves and dry the soil further.' },
      ] },
    ],
    optimalPath: [{ decisionId: 'd1', optionId: 'opt_water' }],
    prompt: 'Choose the best action for a wilted plant.',
    explanation: 'Checking soil moisture and watering only when dry is the sensible, evidence-based care step.',
    objective: 'Apply evidence-based reasoning to plant care.',
    topic: 'life', subtopic: 'plants-animals', difficulty: 3, gradeMin: 7, gradeMax: 9,
    hints: [{ level: 1, text: 'Wilting most often means too little water.' }], ...S,
  }),
  scenario({
    scenarioText: 'Your class plans to measure rainfall outside, but dark storm clouds are gathering and lightning is near.',
    entryDecision: 'd1',
    decisions: [
      { id: 'd1', text: 'What should the group do?', options: [
        { id: 'opt_postpone', text: 'Postpone the outdoor measurement until the storm passes', nextDecision: null, outcomeText: 'Staying indoors during lightning is the safe choice — correct.' },
        { id: 'opt_tree', text: 'Stand under the tallest tree to keep dry', nextDecision: null, outcomeText: 'Tall trees attract lightning and are very dangerous.' },
        { id: 'opt_metal', text: 'Hold a metal pole up to measure the storm', nextDecision: null, outcomeText: 'Metal objects attract lightning; never hold them during a storm.' },
      ] },
    ],
    optimalPath: [{ decisionId: 'd1', optionId: 'opt_postpone' }],
    prompt: 'Choose the safest action during a thunderstorm.',
    explanation: 'Postponing outdoor work during lightning keeps everyone safe; no measurement is worth the risk.',
    objective: 'Apply weather safety decisions.',
    topic: 'earth-space', subtopic: 'weather-climate', difficulty: 2, gradeMin: 7, gradeMax: 9,
    hints: [{ level: 1, text: 'Lightning is attracted to tall, metal objects.' }], ...S,
  }),

  numberLogic({ problem: 'A 4 kg trolley accelerates at 3 m/s². Using force = mass × acceleration, what force is needed?', answerFormat: 'integer', answer: { type: 'exact', value: 12 }, prompt: 'A 4 kg trolley accelerates at 3 m/s². Using force = mass × acceleration, what force is needed in newtons?', explanation: 'Force = 4 × 3 = 12 N.', objective: 'Calculate force from mass and acceleration.', topic: 'physics', subtopic: 'forces-motion', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Multiply the mass by the acceleration.' }], ...S }),
  numberLogic({ problem: 'A lamp draws a current of 2 A when connected to a 6 V supply. Using voltage = current × resistance, what is the lamp resistance?', answerFormat: 'decimal', answer: { type: 'exact', value: 3 }, prompt: 'A lamp draws a current of 2 A when connected to a 6 V supply. Using voltage = current × resistance, what is the resistance in ohms?', explanation: 'Resistance = 6 ÷ 2 = 3 Ω.', objective: 'Calculate resistance using the voltage–current relationship.', topic: 'physics', subtopic: 'electricity-magnetism', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Divide the voltage by the current.' }], ...S }),
  numberLogic({ problem: 'A reaction releases 60 cm³ of gas in 30 seconds. What is the average rate of gas production?', answerFormat: 'integer', answer: { type: 'exact', value: 2 }, prompt: 'A reaction releases 60 cm³ of gas in 30 seconds. What is the average rate of gas production in cm³ per second?', explanation: 'Rate = 60 ÷ 30 = 2 cm³ per second.', objective: 'Calculate the average rate of a reaction.', topic: 'chemistry', subtopic: 'reactions-changes', difficulty: 3, gradeMin: 7, gradeMax: 9, hints: [{ level: 1, text: 'Divide the gas volume by the time taken.' }], ...S }),
]