/**
 * Content Bank — Science, Level 4 (Task 5.14, Batch 1).
 * Blueprint §6.1 L4 (DD10 MT5 OR10 ST5 FC15 II20 PA10 ME5 SC15 NL5),
 * topics §7.4 L4, difficulty §5.3 L4 (D2 25 / D3 45 / D4 30).
 */
import { src, sorting, matching, fillComplete, imageInteraction, pattern, ordering, numberLogic, scenario } from './helpers.mjs'

const S = { level: 4, ...src('science') }

export default [
  fillComplete({ template: 'The SI unit of force is the ___.', blanks: [{ id: 'b1', type: 'text', label: 'unit', maxLength: 10 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['newton', 'newtons'] }], prompt: 'The SI unit of force is the ___.', explanation: 'Force is measured in newtons (N), named after Isaac Newton.', objective: 'Name the SI unit of force.', topic: 'physics', subtopic: 'forces-motion', difficulty: 2, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'It is abbreviated with a capital N.' }], ...S }),
  fillComplete({ template: 'Density equals mass divided by ___.', blanks: [{ id: 'b1', type: 'text', label: 'quantity', maxLength: 10 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['volume'] }], prompt: 'Density equals mass divided by ___.', explanation: 'Density = mass ÷ volume.', objective: 'State the formula for density.', topic: 'physics', subtopic: 'matter', difficulty: 2, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'It is the space the matter takes up.' }], ...S }),
  fillComplete({ template: 'A block has mass 200 g and volume 50 cm³. Its density is ___ g/cm³.', blanks: [{ id: 'b1', type: 'number', label: 'density (g/cm³)', maxLength: 6 }], numeric: [{ blankId: 'b1', value: 4, tolerance: 0 }], prompt: 'A block has mass 200 g and volume 50 cm³. Its density is ___ g/cm³.', explanation: '200 ÷ 50 = 4 g/cm³.', objective: 'Calculate density from mass and volume.', topic: 'physics', subtopic: 'matter', difficulty: 3, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'Divide the mass by the volume.' }], ...S }),
  fillComplete({ template: 'Respiration that releases energy from glucose using oxygen is called ___ respiration.', blanks: [{ id: 'b1', type: 'text', label: 'type of respiration', maxLength: 12 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['aerobic'] }], prompt: 'Respiration that releases energy from glucose using oxygen is called ___ respiration.', explanation: 'Aerobic respiration uses oxygen to release energy from glucose efficiently.', objective: 'Name oxygen-using respiration.', topic: 'life', subtopic: 'body-systems', difficulty: 3, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'It is the opposite of anaerobic.' }], ...S }),

  imageInteraction({ image: { ref: 'question-media/science/life/food-web.png', alt: 'A food web diagram with arrows from grass to rabbit and mouse, from rabbit and mouse to fox, and from mouse to owl.', role: 'diagram', width: 400, height: 320 }, imageWidth: 400, imageHeight: 320, mode: 'tap', hotspots: [{ id: 'h1', label: 'The apex predator', x: 70, y: 18, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The diagram shows a food web. Tap the apex predator.', explanation: 'The fox is at the top of the web — nothing else feeds on it — so it is the apex predator.', objective: 'Identify an apex predator in a food web.', topic: 'life', subtopic: 'evolution-ecosystems', difficulty: 3, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'Look for the animal with no predators above it.' }], ...S }),
  imageInteraction({ image: { ref: 'question-media/science/life/plant-cell.png', alt: 'Diagram of a plant cell with hotspots on the nucleus, cell wall, chloroplast and mitochondria.', role: 'diagram', width: 400, height: 400 }, imageWidth: 400, imageHeight: 400, mode: 'label', hotspots: [{ id: 'h1', label: 'Nucleus', x: 50, y: 50, radius: 14 }, { id: 'h2', label: 'Cell wall', x: 8, y: 50, radius: 12 }, { id: 'h3', label: 'Chloroplast', x: 65, y: 30, radius: 14 }, { id: 'h4', label: 'Mitochondria', x: 40, y: 75, radius: 14 }], labels: [{ id: 'l1', text: 'Nucleus' }, { id: 'l2', text: 'Cell wall' }, { id: 'l3', text: 'Chloroplast' }, { id: 'l4', text: 'Mitochondria' }], placements: [{ labelId: 'l1', hotspotId: 'h1' }, { labelId: 'l2', hotspotId: 'h2' }, { labelId: 'l3', hotspotId: 'h3' }, { labelId: 'l4', hotspotId: 'h4' }], requiredHotspots: ['h1', 'h2', 'h3', 'h4'], prompt: 'Label the plant cell by placing each label on the correct part.', explanation: 'The nucleus controls the cell, the cell wall is the outer rigid layer, chloroplasts do photosynthesis and mitochondria release energy.', objective: 'Label the parts of a plant cell.', topic: 'life', subtopic: 'cells-organisms', difficulty: 4, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'Chloroplasts are the green, oval structures.' }], ...S }),

  sorting({ items: [{ id: 'i1', label: 'Natural selection favours beneficial traits' }, { id: 'i2', label: 'Individuals evolve during their lifetime' }, { id: 'i3', label: 'Populations evolve over generations' }, { id: 'i4', label: 'Species that cannot adapt may go extinct' }, { id: 'i5', label: 'Evolution happens overnight' }], categories: [{ id: 'c_t', label: 'True' }, { id: 'c_f', label: 'False' }], assignments: [{ itemId: 'i1', categoryId: 'c_t' }, { itemId: 'i2', categoryId: 'c_f' }, { itemId: 'i3', categoryId: 'c_t' }, { itemId: 'i4', categoryId: 'c_t' }, { itemId: 'i5', categoryId: 'c_f' }], prompt: 'Sort each statement as true or false about evolution.', explanation: 'Evolution acts on populations over generations, favouring beneficial traits; individuals do not evolve, and it does not happen overnight.', objective: 'Evaluate statements about evolution.', topic: 'life', subtopic: 'evolution-ecosystems', difficulty: 3, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'Ask: does this happen to a whole population across generations?' }], ...S }),

  ordering({ items: [{ id: 'o1', label: 'Deposition' }, { id: 'o2', label: 'Erosion' }, { id: 'o3', label: 'Weathering' }, { id: 'o4', label: 'Compaction' }], order: ['o3', 'o2', 'o1', 'o4'], prompt: 'Arrange the steps of the rock cycle in order.', explanation: 'Weathering breaks rocks, erosion moves the fragments, deposition drops them and compaction forms sedimentary rock.', objective: 'Order the stages of the rock cycle.', topic: 'earth-space', subtopic: 'rock-cycle', difficulty: 2, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'Breaking comes before moving, which comes before settling.' }], ...S }),

  matching({ leftItems: [{ id: 'l1', text: 'Weathering' }, { id: 'l2', text: 'Erosion' }, { id: 'l3', text: 'Deposition' }, { id: 'l4', text: 'Compaction' }], rightItems: [{ id: 'r1', text: 'Breaks rocks apart' }, { id: 'r2', text: 'Moves sediment away' }, { id: 'r3', text: 'Drops sediment' }, { id: 'r4', text: 'Forms sedimentary rock' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each geological process to its effect.', explanation: 'Weathering breaks rocks, erosion moves sediment, deposition drops it and compaction builds sedimentary rock.', objective: 'Match rock-cycle processes to effects.', topic: 'earth-space', subtopic: 'rock-cycle', difficulty: 2, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'Think of each as a step in the rock cycle.' }], ...S }),

  pattern({ sequence: [{ id: 'e1', text: 'New moon' }, { id: 'e2', text: 'Waxing crescent' }, { id: 'e3', text: 'First quarter' }, { id: 'e4', text: 'Waxing gibbous' }], interaction: 'complete-sequence', candidates: [{ id: 'c1', text: 'Full moon' }, { id: 'c2', text: 'Last quarter' }, { id: 'c3', text: 'Eclipse' }, { id: 'c4', text: 'Meteor' }], answer: { type: 'candidate', rule: 'The waxing phase cycle.', acceptableIds: ['c1'] }, prompt: 'Choose the next phase: New moon, Waxing crescent, First quarter, Waxing gibbous, …', explanation: 'As the lit portion grows it reaches the full moon.', objective: 'Extend the sequence of moon phases.', topic: 'earth-space', subtopic: 'solar-system', difficulty: 2, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'The lit part keeps growing until it is fully lit.' }], ...S }),

  numberLogic({ problem: 'A wave has a frequency of 2 Hz and a wavelength of 3 m. What is its speed?', answerFormat: 'integer', answer: { type: 'exact', value: 6 }, prompt: 'A wave has a frequency of 2 Hz and a wavelength of 3 m. What is its speed in m/s?', explanation: 'Wave speed = frequency × wavelength = 2 × 3 = 6 m/s.', objective: 'Calculate wave speed from frequency and wavelength.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 3, gradeMin: 8, gradeMax: 11, hints: [{ level: 1, text: 'Multiply frequency by wavelength.' }], ...S }),

  scenario({
    scenarioText: 'You want to test whether the amount of light affects how tall plants grow. You have two identical plants, the same soil and the same watering schedule.',
    entryDecision: 'd1',
    decisions: [
      { id: 'd1', text: 'What is the independent variable?', options: [
        { id: 'opt_light', text: 'The amount of light', nextDecision: 'd2', outcomeText: 'Correct — the variable you change is the amount of light.' },
        { id: 'opt_water', text: 'The amount of water', nextDecision: null, outcomeText: 'Watering is kept the same, so it is a controlled variable.' },
        { id: 'opt_soil', text: 'The type of soil', nextDecision: null, outcomeText: 'Soil is kept the same, so it is a controlled variable.' },
      ] },
      { id: 'd2', text: 'What should you measure as the outcome?', options: [
        { id: 'opt_height', text: 'Plant height over time', nextDecision: null, outcomeText: 'Height over time is the dependent variable — the correct measure.' },
        { id: 'opt_pot', text: 'The colour of the pot', nextDecision: null, outcomeText: 'Pot colour does not depend on light and is not a scientific outcome.' },
        { id: 'opt_soil2', text: 'The amount of soil', nextDecision: null, outcomeText: 'Soil amount is controlled, not measured.' },
      ] },
    ],
    optimalPath: [{ decisionId: 'd1', optionId: 'opt_light' }, { decisionId: 'd2', optionId: 'opt_height' }],
    prompt: 'Choose the independent variable and the outcome to measure.',
    explanation: 'The independent variable is what you change (light), and the dependent variable is what you measure (height over time).',
    objective: 'Design a fair experiment with clear variables.',
    topic: 'inquiry', subtopic: 'scientific-method', difficulty: 3, gradeMin: 8, gradeMax: 11,
    hints: [{ level: 1, text: 'You change one thing and measure the result.' }], ...S,
  }),
]