/**
 * Content Bank — Science, Level 2 (Task 5.14, Batch 1).
 * Blueprint §6.1 L2 (DD20 MT15 OR10 ST10 FC15 II10 PA5 ME10 SC0 NL5),
 * topics §7.2 L2, difficulty §5.3 L2 (D1 35 / D2 40 / D3 20 / D4 5).
 */
import { src, dragDrop, sorting, matching, fillComplete, imageInteraction, pattern, memory, ordering, numberLogic } from './helpers.mjs'

const S = { level: 2, ...src('science') }

export default [
  dragDrop({ items: [{ id: 'i1', label: 'Eagle' }, { id: 'i2', label: 'Snail' }, { id: 'i3', label: 'Frog' }, { id: 'i4', label: 'Earthworm' }, { id: 'i5', label: 'Dolphin' }, { id: 'i6', label: 'Jellyfish' }], zones: [{ id: 'z_v', label: 'Vertebrate' }, { id: 'z_i', label: 'Invertebrate' }], mappings: [{ itemId: 'i1', zoneId: 'z_v' }, { itemId: 'i2', zoneId: 'z_i' }, { itemId: 'i3', zoneId: 'z_v' }, { itemId: 'i4', zoneId: 'z_i' }, { itemId: 'i5', zoneId: 'z_v' }, { itemId: 'i6', zoneId: 'z_i' }], prompt: 'Classify each animal as a vertebrate or an invertebrate.', explanation: 'Vertebrates have a backbone (eagle, frog, dolphin); invertebrates do not (snail, earthworm, jellyfish).', objective: 'Classify animals by whether they have a backbone.', topic: 'life', subtopic: 'plants-animals', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Look for an internal backbone (spine).' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Salt water' }, { id: 'i2', label: 'Sand in water' }, { id: 'i3', label: 'Sugar in tea' }, { id: 'i4', label: 'Oil in water' }, { id: 'i5', label: 'Lemonade' }, { id: 'i6', label: 'Muddy water' }], zones: [{ id: 'z_sol', label: 'Solution' }, { id: 'z_ns', label: 'Not a solution' }], mappings: [{ itemId: 'i1', zoneId: 'z_sol' }, { itemId: 'i2', zoneId: 'z_ns' }, { itemId: 'i3', zoneId: 'z_sol' }, { itemId: 'i4', zoneId: 'z_ns' }, { itemId: 'i5', zoneId: 'z_sol' }, { itemId: 'i6', zoneId: 'z_ns' }], prompt: 'Classify each mixture as a solution or not a solution.', explanation: 'In a solution the substance dissolves completely; sand, oil and mud settle or float instead.', objective: 'Classify mixtures as solutions or not.', topic: 'chemistry', subtopic: 'matter-particles', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Does the substance dissolve and stay mixed?' }], ...S }),
  dragDrop({ items: [{ id: 'i1', label: 'Sun' }, { id: 'i2', label: 'Moon' }, { id: 'i3', label: 'Torch' }, { id: 'i4', label: 'Mirror' }, { id: 'i5', label: 'Lamp' }, { id: 'i6', label: 'Firefly' }], zones: [{ id: 'z_src', label: 'Source of light' }, { id: 'z_rfl', label: 'Reflects light only' }], mappings: [{ itemId: 'i1', zoneId: 'z_src' }, { itemId: 'i2', zoneId: 'z_rfl' }, { itemId: 'i3', zoneId: 'z_src' }, { itemId: 'i4', zoneId: 'z_rfl' }, { itemId: 'i5', zoneId: 'z_src' }, { itemId: 'i6', zoneId: 'z_src' }], prompt: 'Sort each object as a source of light or a reflector.', explanation: 'The sun, torch, lamp and firefly make their own light; the moon and mirror only reflect it.', objective: 'Distinguish light sources from reflectors.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 1, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Does it produce the light itself?' }], ...S }),

  sorting({ items: [{ id: 'i1', label: 'Chicken' }, { id: 'i2', label: 'Rabbit' }, { id: 'i3', label: 'Turtle' }, { id: 'i4', label: 'Dog' }, { id: 'i5', label: 'Snake' }, { id: 'i6', label: 'Cow' }], categories: [{ id: 'c_egg', label: 'Lay eggs' }, { id: 'c_birth', label: 'Give birth' }], assignments: [{ itemId: 'i1', categoryId: 'c_egg' }, { itemId: 'i2', categoryId: 'c_birth' }, { itemId: 'i3', categoryId: 'c_egg' }, { itemId: 'i4', categoryId: 'c_birth' }, { itemId: 'i5', categoryId: 'c_egg' }, { itemId: 'i6', categoryId: 'c_birth' }], prompt: 'Sort each animal by how it reproduces.', explanation: 'Chickens, turtles and snakes lay eggs; rabbits, dogs and cows give birth to live young.', objective: 'Classify animals by reproduction method.', topic: 'life', subtopic: 'plants-animals', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Think of a chicken egg and a puppy.' }], ...S }),

  matching({ leftItems: [{ id: 'l1', text: 'Heart' }, { id: 'l2', text: 'Lungs' }, { id: 'l3', text: 'Stomach' }, { id: 'l4', text: 'Brain' }], rightItems: [{ id: 'r1', text: 'Pumps blood' }, { id: 'r2', text: 'Exchange of gases' }, { id: 'r3', text: 'Digests food' }, { id: 'r4', text: 'Controls the body' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each organ to its job.', explanation: 'The heart pumps blood, the lungs exchange gases, the stomach digests food and the brain controls the body.', objective: 'Match major organs to their functions.', topic: 'life', subtopic: 'body-systems', difficulty: 1, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Think about what each organ does for the body.' }], ...S }),
  matching({ leftItems: [{ id: 'l1', text: 'Melting' }, { id: 'l2', text: 'Freezing' }, { id: 'l3', text: 'Evaporation' }, { id: 'l4', text: 'Condensation' }], rightItems: [{ id: 'r1', text: 'Solid to liquid' }, { id: 'r2', text: 'Liquid to solid' }, { id: 'r3', text: 'Liquid to gas' }, { id: 'r4', text: 'Gas to liquid' }], pairs: [{ leftId: 'l1', rightId: 'r1' }, { leftId: 'l2', rightId: 'r2' }, { leftId: 'l3', rightId: 'r3' }, { leftId: 'l4', rightId: 'r4' }], prompt: 'Match each change of state to its description.', explanation: 'Melting is solid to liquid, freezing is liquid to solid, evaporation is liquid to gas and condensation is gas to liquid.', objective: 'Match changes of state to their direction.', topic: 'chemistry', subtopic: 'matter-particles', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Work out whether the substance heats up or cools down.' }], ...S }),

  ordering({ items: [{ id: 'o1', label: 'Fox' }, { id: 'o2', label: 'Grass' }, { id: 'o3', label: 'Rabbit' }], order: ['o2', 'o3', 'o1'], prompt: 'Arrange this food chain from producer to top consumer.', explanation: 'Grass is the producer, the rabbit eats the grass and the fox eats the rabbit.', objective: 'Order a food chain.', topic: 'life', subtopic: 'evolution-ecosystems', difficulty: 1, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Start with the organism that makes its own food.' }], ...S }),

  fillComplete({ template: 'Plants make their own food through ___.', blanks: [{ id: 'b1', type: 'text', label: 'process', maxLength: 20 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['photosynthesis'] }], prompt: 'Plants make their own food through ___.', explanation: 'Photosynthesis uses sunlight, water and carbon dioxide to make food in the leaves.', objective: 'Name the food-making process in plants.', topic: 'life', subtopic: 'plants-animals', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'It happens in the leaves using sunlight.' }], ...S }),
  fillComplete({ template: 'Sound is measured in units called ___.', blanks: [{ id: 'b1', type: 'text', label: 'unit', maxLength: 12 }], answers: [{ blankId: 'b1', type: 'text', accepted: ['decibels'] }], prompt: 'Sound is measured in units called ___.', explanation: 'Loudness is measured in decibels (dB).', objective: 'Name the unit of loudness.', topic: 'physics', subtopic: 'waves-light-sound', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'It is abbreviated dB.' }], ...S }),
  fillComplete({ template: 'A simple pendulum swings 40 times in 80 seconds. It swings ___ times per second.', blanks: [{ id: 'b1', type: 'number', label: 'swings per second', maxLength: 6 }], numeric: [{ blankId: 'b1', value: 0.5, tolerance: 0.001 }], prompt: 'A simple pendulum swings 40 times in 80 seconds. It swings ___ times per second.', explanation: '40 swings ÷ 80 seconds = 0.5 swings per second.', objective: 'Calculate frequency from a count and time.', topic: 'physics', subtopic: 'forces-motion', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Divide the number of swings by the time.' }], ...S }),

  imageInteraction({ image: { ref: 'question-media/science/inquiry/rainfall-bar-chart.png', alt: 'Bar chart of monthly rainfall with the tallest bar in July.', role: 'diagram', width: 400, height: 320 }, imageWidth: 400, imageHeight: 320, mode: 'tap', hotspots: [{ id: 'h1', label: 'July (the wettest month)', x: 52, y: 20, radius: 12 }], requiredHotspots: ['h1'], prompt: 'The bar chart shows monthly rainfall. Tap the wettest month.', explanation: 'July has the tallest bar, so it receives the most rainfall.', objective: 'Read the tallest bar in a bar chart.', topic: 'inquiry', subtopic: 'data-graphing', difficulty: 1, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'The tallest bar shows the greatest rainfall.' }], ...S }),

  pattern({ sequence: [{ id: 'e1', text: 'New moon' }, { id: 'e2', text: 'Crescent' }, { id: 'e3', text: 'Half moon' }], interaction: 'complete-sequence', candidates: [{ id: 'c1', text: 'Full moon' }, { id: 'c2', text: 'Eclipse' }, { id: 'c3', text: 'Comet' }, { id: 'c4', text: 'Nebula' }], answer: { type: 'candidate', rule: 'The growing phase of the Moon.', acceptableIds: ['c1'] }, prompt: 'Choose the next phase: New moon, Crescent, Half moon, …', explanation: 'The lit part grows to a gibbous then a full moon.', objective: 'Order the phases of the Moon.', topic: 'earth-space', subtopic: 'solar-system', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'The Moon is gaining more and more light.' }], ...S }),

  memory({ cards: [{ id: 'c1', text: 'Earth' }, { id: 'c2', text: '3rd' }, { id: 'c3', text: 'Mars' }, { id: 'c4', text: '4th' }, { id: 'c5', text: 'Venus' }, { id: 'c6', text: '2nd' }, { id: 'c7', text: 'Jupiter' }, { id: 'c8', text: '5th' }], groups: [{ groupId: 'g1', cardIds: ['c1', 'c2'] }, { groupId: 'g2', cardIds: ['c3', 'c4'] }, { groupId: 'g3', cardIds: ['c5', 'c6'] }, { groupId: 'g4', cardIds: ['c7', 'c8'] }], revealSeconds: 12, recallPrompt: 'Remember each planet with its position from the Sun.', deckType: 'pairs', prompt: 'Memorise each planet with its position, then match the pairs.', explanation: 'Venus is 2nd, Earth 3rd, Mars 4th and Jupiter 5th from the Sun.', objective: 'Recall planet positions from the Sun.', topic: 'earth-space', subtopic: 'solar-system', difficulty: 2, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Each pair links a planet to its order from the Sun.' }], ...S }),

  numberLogic({ problem: 'A runner completes 2 laps of a 400 m track. How far did they run?', answerFormat: 'integer', answer: { type: 'exact', value: 800 }, prompt: 'A runner completes 2 laps of a 400 m track. How far did they run?', explanation: '2 × 400 m = 800 m.', objective: 'Multiply a distance by a number of laps.', topic: 'inquiry', subtopic: 'measurement-units', difficulty: 1, gradeMin: 6, gradeMax: 8, hints: [{ level: 1, text: 'Multiply the lap length by the number of laps.' }], ...S }),
]