/**
 * Content Bank — Technology, Level 1 (Task 5.14, Batch 2).
 * Blueprint §6.2 L1 (DD20 MT15 OR5 ST15 FC15 II5 PA10 ME10 SC0 NL5),
 * topics §7.2 L1, difficulty §5.3 L1 (D1 70 / D2 25 / D3 5).
 */
import { src, dragDrop, sorting, matching, fillComplete, pattern, memory, ordering, numberLogic } from './helpers.mjs'

const S = { level: 1, ...src('technology') }

export default [
  dragDrop({
    items: [
      { id: 'i1', label: 'Keyboard' },
      { id: 'i2', label: 'Web Browser' },
      { id: 'i3', label: 'Monitor' },
      { id: 'i4', label: 'Paint App' },
      { id: 'i5', label: 'Mouse' },
      { id: 'i6', label: 'Word Processor' },
    ],
    zones: [
      { id: 'z_hw', label: 'Hardware' },
      { id: 'z_sw', label: 'Software' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_hw' },
      { itemId: 'i2', zoneId: 'z_sw' },
      { itemId: 'i3', zoneId: 'z_hw' },
      { itemId: 'i4', zoneId: 'z_sw' },
      { itemId: 'i5', zoneId: 'z_hw' },
      { itemId: 'i6', zoneId: 'z_sw' },
    ],
    prompt: 'Classify each computer item as Hardware or Software.',
    explanation: 'Hardware refers to physical parts like keyboards, monitors and mice. Software refers to programs like browsers and word processors.',
    objective: 'Distinguish between computer hardware and software.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Can you physically touch the object?' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'Keep passwords secret' },
      { id: 'i2', label: 'Share home address with strangers' },
      { id: 'i3', label: 'Use strong passwords' },
      { id: 'i4', label: 'Click unknown email links' },
      { id: 'i5', label: 'Ask adult before downloading' },
    ],
    categories: [
      { id: 'c_safe', label: 'Safe online habit' },
      { id: 'c_unsafe', label: 'Unsafe online habit' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_safe' },
      { itemId: 'i2', categoryId: 'c_unsafe' },
      { itemId: 'i3', categoryId: 'c_safe' },
      { itemId: 'i4', categoryId: 'c_unsafe' },
      { itemId: 'i5', categoryId: 'c_safe' },
    ],
    prompt: 'Sort each habit as a safe or unsafe online habit.',
    explanation: 'Keeping passwords private, using strong passwords, and asking adults before downloads keep you safe online.',
    objective: 'Identify safe and unsafe internet practices.',
    topic: 'digital-literacy',
    subtopic: 'online-safety-ethics',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Think about protecting your personal information.' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: '.jpg' },
      { id: 'l2', text: '.mp3' },
      { id: 'l3', text: '.txt' },
      { id: 'l4', text: '.pdf' },
    ],
    rightItems: [
      { id: 'r1', text: 'Image file' },
      { id: 'r2', text: 'Audio file' },
      { id: 'r3', text: 'Text document' },
      { id: 'r4', text: 'PDF document' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each file extension to its file type.',
    explanation: '.jpg is an image format, .mp3 is audio, .txt is plain text, and .pdf is a formatted document.',
    objective: 'Match common file extensions to file types.',
    topic: 'digital-literacy',
    subtopic: 'files-formats',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which extension is used for photos?' }],
    ...S,
  }),

  fillComplete({
    template: 'The part of a computer that processes instructions is called the ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'component', maxLength: 10 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['cpu', 'processor'] }],
    prompt: 'The part of a computer that processes instructions is called the ___.',
    explanation: 'The CPU (Central Processing Unit) acts as the brain of the computer.',
    objective: 'Identify the CPU as the main processor.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'It stands for Central Processing Unit.' }],
    ...S,
  }),

  ordering({
    items: [
      { id: 'o1', label: 'Press power button' },
      { id: 'o2', label: 'Wait for operating system to load' },
      { id: 'o3', label: 'Enter password' },
      { id: 'o4', label: 'Open application' },
    ],
    order: ['o1', 'o2', 'o3', 'o4'],
    prompt: 'Arrange the steps to start using a computer application in order.',
    explanation: 'First press power, wait for OS load, log in with password, then open your app.',
    objective: 'Order the steps for turning on and logging into a computer.',
    topic: 'programming',
    subtopic: 'algorithms',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Start with turning the physical device on.' }],
    ...S,
  }),

  pattern({
    sequence: [
      { id: 'e1', text: '0' },
      { id: 'e2', text: '1' },
      { id: 'e3', text: '0' },
      { id: 'e4', text: '1' },
      { id: 'e5', text: '0' },
    ],
    interaction: 'complete-sequence',
    candidates: [
      { id: 'c1', text: '1' },
      { id: 'c2', text: '0' },
      { id: 'c3', text: '2' },
      { id: 'c4', text: '10' },
    ],
    answer: { type: 'candidate', rule: 'Alternating binary pattern.', acceptableIds: ['c1'] },
    prompt: 'Choose the next bit in the binary sequence: 0, 1, 0, 1, 0, …',
    explanation: 'The sequence alternates between 0 and 1, so the next bit is 1.',
    objective: 'Extend a simple alternating binary sequence.',
    topic: 'computing',
    subtopic: 'data-representation',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Look at how 0 and 1 take turns.' }],
    ...S,
  }),

  memory({
    cards: [
      { id: 'c1', text: 'Printer' },
      { id: 'c2', text: 'Paper output' },
      { id: 'c3', text: 'Keyboard' },
      { id: 'c4', text: 'Typing text' },
      { id: 'c5', text: 'Speaker' },
      { id: 'c6', text: 'Sound output' },
      { id: 'c7', text: 'Microphone' },
      { id: 'c8', text: 'Voice input' },
    ],
    groups: [
      { groupId: 'g1', cardIds: ['c1', 'c2'] },
      { groupId: 'g2', cardIds: ['c3', 'c4'] },
      { groupId: 'g3', cardIds: ['c5', 'c6'] },
      { groupId: 'g4', cardIds: ['c7', 'c8'] },
    ],
    revealSeconds: 12,
    recallPrompt: 'Remember each device with its function.',
    deckType: 'pairs',
    prompt: 'Memorise each device with its main function, then match the pairs.',
    explanation: 'Printers produce paper output, keyboards type text, speakers output sound, and microphones take voice input.',
    objective: 'Match computer peripherals to their functions.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Match each device to what it produces or receives.' }],
    ...S,
  }),

  numberLogic({
    problem: 'A photo file takes 2 MB of storage. How many megabytes will 4 photos take?',
    answerFormat: 'integer',
    answer: { type: 'exact', value: 8 },
    prompt: 'A photo file takes 2 MB of storage. How many megabytes will 4 photos take?',
    explanation: '2 MB × 4 = 8 MB total storage.',
    objective: 'Calculate total file storage size.',
    topic: 'computing',
    subtopic: 'data-representation',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Multiply the size of one photo by 4.' }],
    ...S,
  }),

  dragDrop({
    items: [
      { id: 'i1', label: 'Mouse' },
      { id: 'i2', label: 'Speaker' },
      { id: 'i3', label: 'Keyboard' },
      { id: 'i4', label: 'Monitor' },
      { id: 'i5', label: 'Microphone' },
      { id: 'i6', label: 'Printer' },
    ],
    zones: [
      { id: 'z_in', label: 'Input Device' },
      { id: 'z_out', label: 'Output Device' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_in' },
      { itemId: 'i2', zoneId: 'z_out' },
      { itemId: 'i3', zoneId: 'z_in' },
      { itemId: 'i4', zoneId: 'z_out' },
      { itemId: 'i5', zoneId: 'z_in' },
      { itemId: 'i6', zoneId: 'z_out' },
    ],
    prompt: 'Classify each device as an Input Device or an Output Device.',
    explanation: 'Input devices send data to the computer (mouse, keyboard, microphone). Output devices display or produce data (speaker, monitor, printer).',
    objective: 'Classify computer peripherals into input and output devices.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Does it send info into the computer or output info to you?' }],
    ...S,
  }),

  fillComplete({
    template: 'A web address used to find a page on the internet is called a ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'web address term', maxLength: 10 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['url', 'web address', 'link'] }],
    prompt: 'A web address used to find a page on the internet is called a ___.',
    explanation: 'URL stands for Uniform Resource Locator, which is the web address of a page.',
    objective: 'Name the web address term (URL).',
    topic: 'computing',
    subtopic: 'networks-internet',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'It is a 3-letter abbreviation starting with U.' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'Ctrl + C' },
      { id: 'l2', text: 'Ctrl + V' },
      { id: 'l3', text: 'Ctrl + Z' },
      { id: 'l4', text: 'Ctrl + S' },
    ],
    rightItems: [
      { id: 'r1', text: 'Copy' },
      { id: 'r2', text: 'Paste' },
      { id: 'r3', text: 'Undo' },
      { id: 'r4', text: 'Save' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each keyboard shortcut to its action.',
    explanation: 'Ctrl+C copies, Ctrl+V pastes, Ctrl+Z undoes the last action, and Ctrl+S saves.',
    objective: 'Match common keyboard shortcuts to actions.',
    topic: 'digital-tools',
    subtopic: 'documents',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Ctrl + C stands for Copy.' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'Type username' },
      { id: 'i2', label: 'Calculate total cost' },
      { id: 'i3', label: 'Print receipt' },
      { id: 'i4', label: 'Press enter button' },
      { id: 'i5', label: 'Multiply price by quantity' },
      { id: 'i6', label: 'Display welcome message' },
    ],
    categories: [
      { id: 'c_in', label: 'Input' },
      { id: 'c_proc', label: 'Processing' },
      { id: 'c_out', label: 'Output' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_in' },
      { itemId: 'i2', categoryId: 'c_proc' },
      { itemId: 'i3', categoryId: 'c_out' },
      { itemId: 'i4', categoryId: 'c_in' },
      { itemId: 'i5', categoryId: 'c_proc' },
      { itemId: 'i6', categoryId: 'c_out' },
    ],
    prompt: 'Sort each computer action into Input, Processing, or Output.',
    explanation: 'Input receives user data, Processing performs calculations, and Output presents results.',
    objective: 'Categorize computer tasks into Input, Processing, and Output.',
    topic: 'programming',
    subtopic: 'algorithms',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Is data entering, being calculated, or being shown?' }],
    ...S,
  }),

  fillComplete({
    template: 'One byte is made up of ___ bits.',
    blanks: [{ id: 'b1', type: 'number', label: 'number of bits', maxLength: 4 }],
    numeric: [{ blankId: 'b1', value: 8, tolerance: 0 }],
    prompt: 'One byte is made up of ___ bits.',
    explanation: 'There are 8 bits in 1 byte.',
    objective: 'State the number of bits in a byte.',
    topic: 'computing',
    subtopic: 'data-representation',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'It is a number between 5 and 10.' }],
    ...S,
  }),

  pattern({
    sequence: [
      { id: 'e1', text: 'A1' },
      { id: 'e2', text: 'B1' },
      { id: 'e3', text: 'C1' },
      { id: 'e4', text: 'D1' },
    ],
    interaction: 'complete-sequence',
    candidates: [
      { id: 'c1', text: 'E1' },
      { id: 'c2', text: 'E2' },
      { id: 'c3', text: 'D2' },
      { id: 'c4', text: 'F1' },
    ],
    answer: { type: 'candidate', rule: 'Next column in row 1.', acceptableIds: ['c1'] },
    prompt: 'Choose the next cell coordinate in a spreadsheet row: A1, B1, C1, D1, …',
    explanation: 'Moving right across row 1 advances the column letter from D to E, giving E1.',
    objective: 'Identify the next cell coordinate in a spreadsheet row.',
    topic: 'digital-tools',
    subtopic: 'spreadsheets',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'The letter increases alphabetically while the row number stays 1.' }],
    ...S,
  }),

  memory({
    cards: [
      { id: 'c1', text: 'RAM' },
      { id: 'c2', text: 'Temporary memory' },
      { id: 'c3', text: 'ROM' },
      { id: 'c4', text: 'Permanent memory' },
      { id: 'c5', text: 'Wi-Fi' },
      { id: 'c6', text: 'Wireless network' },
      { id: 'c7', text: 'Bug' },
      { id: 'c8', text: 'Code error' },
    ],
    groups: [
      { groupId: 'g1', cardIds: ['c1', 'c2'] },
      { groupId: 'g2', cardIds: ['c3', 'c4'] },
      { groupId: 'g3', cardIds: ['c5', 'c6'] },
      { groupId: 'g4', cardIds: ['c7', 'c8'] },
    ],
    revealSeconds: 12,
    recallPrompt: 'Remember each technology term with its description.',
    deckType: 'pairs',
    prompt: 'Memorise each technology term with its description, then match the pairs.',
    explanation: 'RAM is temporary memory, ROM is permanent startup memory, Wi-Fi is a wireless network, and a bug is an error in code.',
    objective: 'Match fundamental tech terminology.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Pair abbreviations and terms with their meanings.' }],
    ...S,
  }),

  dragDrop({
    items: [
      { id: 'i1', label: 'Hard Drive (HDD)' },
      { id: 'i2', label: 'USB Flash Drive' },
      { id: 'i3', label: 'Solid State Drive (SSD)' },
      { id: 'i4', label: 'SD Memory Card' },
      { id: 'i5', label: 'Motherboard Storage' },
      { id: 'i6', label: 'External Portable Hard Drive' },
    ],
    zones: [
      { id: 'z_int', label: 'Internal Storage' },
      { id: 'z_rem', label: 'Removable/External Storage' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_int' },
      { itemId: 'i2', zoneId: 'z_rem' },
      { itemId: 'i3', zoneId: 'z_int' },
      { itemId: 'i4', zoneId: 'z_rem' },
      { itemId: 'i5', zoneId: 'z_int' },
      { itemId: 'i6', zoneId: 'z_rem' },
    ],
    prompt: 'Classify each computer storage device as Internal Storage or Removable/External Storage.',
    explanation: 'Internal storage (HDD, SSD, motherboard storage) resides inside the computer case. Removable/external storage (USB drive, SD card, portable drive) can be detached easily.',
    objective: 'Classify computer storage devices by portability.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Can the device be unplugged and carried in your pocket?' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'photo.jpg' },
      { id: 'i2', label: 'report.docx' },
      { id: 'i3', label: 'song.mp3' },
      { id: 'i4', label: 'diagram.png' },
      { id: 'i5', label: 'manual.pdf' },
      { id: 'i6', label: 'podcast.wav' },
    ],
    categories: [
      { id: 'c_img', label: 'Image File' },
      { id: 'c_doc', label: 'Document File' },
      { id: 'c_aud', label: 'Audio File' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_img' },
      { itemId: 'i2', categoryId: 'c_doc' },
      { itemId: 'i3', categoryId: 'c_aud' },
      { itemId: 'i4', categoryId: 'c_img' },
      { itemId: 'i5', categoryId: 'c_doc' },
      { itemId: 'i6', categoryId: 'c_aud' },
    ],
    prompt: 'Sort each file name into Image File, Document File, or Audio File based on its extension.',
    explanation: '.jpg and .png are image extensions; .docx and .pdf are document extensions; .mp3 and .wav are audio extensions.',
    objective: 'Identify file types by file extension.',
    topic: 'digital-literacy',
    subtopic: 'file-types',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Look at the letters after the dot in each file name.' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'Variable' },
      { id: 'l2', text: 'Loop' },
      { id: 'l3', text: 'Function' },
      { id: 'l4', text: 'Bug' },
    ],
    rightItems: [
      { id: 'r1', text: 'Container for storing data' },
      { id: 'r2', text: 'Repeats a set of instructions' },
      { id: 'r3', text: 'Reusable block of code' },
      { id: 'r4', text: 'Error in a computer program' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each programming concept to its definition.',
    explanation: 'Variables store data, loops repeat instructions, functions package reusable code, and bugs are program errors.',
    objective: 'Match basic programming terms with their definitions.',
    topic: 'programming',
    subtopic: 'basics',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which term means repeating a block of instructions?' }],
    ...S,
  }),

  fillComplete({
    template: 'A software application used to view web pages on the internet is called a web ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'browser term', maxLength: 10 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['browser', 'browsers'] }],
    prompt: 'A software application used to view web pages on the internet is called a web ___.',
    explanation: 'A web browser (like Chrome, Firefox, or Safari) renders HTML web pages for viewing.',
    objective: 'Identify web browser applications.',
    topic: 'digital-literacy',
    subtopic: 'browsers',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'It is the program you open to browse websites.' }],
    ...S,
  }),

  ordering({
    items: [
      { id: 'o1', label: 'Click "Compose new message"' },
      { id: 'o2', label: 'Type the recipient email address' },
      { id: 'o3', label: 'Write subject line and email text' },
      { id: 'o4', label: 'Click the "Send" button' },
    ],
    order: ['o1', 'o2', 'o3', 'o4'],
    prompt: 'Arrange the steps of sending an email in logical order.',
    explanation: 'You first open a compose window, specify the recipient, compose the message, and finally click send.',
    objective: 'Order the workflow steps of sending an email.',
    topic: 'digital-literacy',
    subtopic: 'communication',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'You must open a new message box before typing recipient details.' }],
    ...S,
  }),

  numberLogic({
    problem: 'If a folder contains 5 video files of 10 MB each and 4 audio files of 5 MB each, what is the total folder size in megabytes?',
    answerFormat: 'integer',
    answer: { type: 'exact', value: 70 },
    prompt: 'If a folder contains 5 video files of 10 MB each and 4 audio files of 5 MB each, what is the total folder size in megabytes?',
    explanation: '(5 × 10 MB) + (4 × 5 MB) = 50 MB + 20 MB = 70 MB total.',
    objective: 'Calculate combined storage of multiple files.',
    topic: 'computing',
    subtopic: 'data-representation',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Calculate video total and audio total separately, then add them.' }],
    ...S,
  }),

  pattern({
    sequence: [
      { id: 'e1', number: 1 },
      { id: 'e2', number: 2 },
      { id: 'e3', number: 4 },
      { id: 'e4', number: 8 },
    ],
    interaction: 'complete-sequence',
    candidates: [
      { id: 'c1', number: 12 },
      { id: 'c2', number: 16 },
      { id: 'c3', number: 10 },
      { id: 'c4', number: 32 },
    ],
    answer: { type: 'candidate', rule: 'Double the previous number (powers of 2).', acceptableIds: ['c2'] },
    prompt: 'Predict the next binary place value in the sequence: 1, 2, 4, 8, …',
    explanation: 'Binary place values double each step: 1, 2, 4, 8, 16.',
    objective: 'Extend a sequence of binary place values.',
    topic: 'computing',
    subtopic: 'data-representation',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Each number is twice the previous number.' }],
    ...S,
  }),

  memory({
    cards: [
      { id: 'c1', text: 'URL' },
      { id: 'c2', text: 'Web page address' },
      { id: 'c3', text: 'HTML' },
      { id: 'c4', text: 'Web page language' },
      { id: 'c5', text: 'IP Address' },
      { id: 'c6', text: 'Unique device network ID' },
      { id: 'c7', text: 'Router' },
      { id: 'c8', text: 'Directs network traffic' },
    ],
    groups: [
      { groupId: 'g1', cardIds: ['c1', 'c2'] },
      { groupId: 'g2', cardIds: ['c3', 'c4'] },
      { groupId: 'g3', cardIds: ['c5', 'c6'] },
      { groupId: 'g4', cardIds: ['c7', 'c8'] },
    ],
    revealSeconds: 12,
    recallPrompt: 'Remember each internet concept with its definition.',
    deckType: 'pairs',
    prompt: 'Memorise each internet term with its definition, then match the pairs.',
    explanation: 'URL is web address, HTML structures web content, IP address identifies network devices, and a router manages data traffic.',
    objective: 'Match networking and web technology terms.',
    topic: 'digital-literacy',
    subtopic: 'browsers',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which term stands for the web address typed into a browser bar?' }],
    ...S,
  }),

  dragDrop({
    items: [
      { id: 'i1', label: 'Windows OS' },
      { id: 'i2', label: 'Web Browser' },
      { id: 'i3', label: 'macOS' },
      { id: 'i4', label: 'Spreadsheet Editor' },
      { id: 'i5', label: 'Linux OS' },
      { id: 'i6', label: 'Photo Editing App' },
    ],
    zones: [
      { id: 'z_sys', label: 'System Software' },
      { id: 'z_app', label: 'Application Software' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_sys' },
      { itemId: 'i2', zoneId: 'z_app' },
      { itemId: 'i3', zoneId: 'z_sys' },
      { itemId: 'i4', zoneId: 'z_app' },
      { itemId: 'i5', zoneId: 'z_sys' },
      { itemId: 'i6', zoneId: 'z_app' },
    ],
    prompt: 'Classify each software program as System Software (Operating System) or Application Software.',
    explanation: 'System software (Windows, macOS, Linux) manages hardware and runs the computer. Application software (browsers, spreadsheets, photo editors) performs specific user tasks.',
    objective: 'Distinguish system software from application software.',
    topic: 'computing',
    subtopic: 'software',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Operating systems manage the hardware, while apps perform specific end-user tasks.' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'Using complex, unique passwords' },
      { id: 'i2', label: 'Sharing password with online friends' },
      { id: 'i3', label: 'Logging off on shared public PCs' },
      { id: 'i4', label: 'Clicking unknown email attachments' },
      { id: 'i5', label: 'Verifying site security (HTTPS lock)' },
      { id: 'i6', label: 'Posting personal home address publicly' },
    ],
    categories: [
      { id: 'c_safe', label: 'Safe Cyber Practice' },
      { id: 'c_unsafe', label: 'Unsafe Cyber Practice' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_safe' },
      { itemId: 'i2', categoryId: 'c_unsafe' },
      { itemId: 'i3', categoryId: 'c_safe' },
      { itemId: 'i4', categoryId: 'c_unsafe' },
      { itemId: 'i5', categoryId: 'c_safe' },
      { itemId: 'i6', categoryId: 'c_unsafe' },
    ],
    prompt: 'Sort each digital habit into Safe Cyber Practice or Unsafe Cyber Practice.',
    explanation: 'Strong passwords, logging out, and verifying HTTPS protect your account. Sharing credentials, opening suspicious files, and publishing private info risk security.',
    objective: 'Identify safe digital citizenship habits.',
    topic: 'digital-literacy',
    subtopic: 'safety',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Consider whether the habit protects your identity and account security.' }],
    ...S,
  }),

  fillComplete({
    template: 'The primary chip that executes instructions in a computer is the ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'processor abbreviation', maxLength: 5 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['cpu', 'processor'] }],
    prompt: 'The primary chip that executes instructions in a computer is the ___.',
    explanation: 'The CPU (Central Processing Unit) carries out software instructions.',
    objective: 'Identify the CPU as the central processor.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Three-letter acronym for Central Processing Unit.' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'Modem' },
      { id: 'l2', text: 'Router' },
      { id: 'l3', text: 'Ethernet Cable' },
      { id: 'l4', text: 'Wi-Fi Adapter' },
    ],
    rightItems: [
      { id: 'r1', text: 'Demodulates ISP signals' },
      { id: 'r2', text: 'Routes network packets to devices' },
      { id: 'r3', text: 'Provides physical wired connection' },
      { id: 'r4', text: 'Enables wireless radio connections' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each network component to its role.',
    explanation: 'Modems translate ISP signals, routers distribute local traffic, ethernet cables connect physically, and Wi-Fi adapters communicate wirelessly.',
    objective: 'Match network hardware components with their functions.',
    topic: 'digital-literacy',
    subtopic: 'browsers',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which item physically plugs into a network port?' }],
    ...S,
  }),

  ordering({
    items: [
      { id: 'o1', label: 'Receive input numbers from user' },
      { id: 'o2', label: 'Calculate sum of input numbers' },
      { id: 'o3', label: 'Store sum in result variable' },
      { id: 'o4', label: 'Display result variable on screen' },
    ],
    order: ['o1', 'o2', 'o3', 'o4'],
    prompt: 'Order the execution steps of an addition program algorithm.',
    explanation: 'The program accepts input, calculates the total, stores the result, and displays it to the user.',
    objective: 'Order basic algorithm execution flow.',
    topic: 'programming',
    subtopic: 'basics',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Input comes first, display comes last.' }],
    ...S,
  }),

  numberLogic({
    problem: 'A download speed is 5 MB per second. How many seconds will it take to download a 40 MB file?',
    answerFormat: 'integer',
    answer: { type: 'exact', value: 8 },
    prompt: 'A download speed is 5 MB per second. How many seconds will it take to download a 40 MB file?',
    explanation: '40 MB ÷ 5 MB/s = 8 seconds.',
    objective: 'Calculate file download duration.',
    topic: 'digital-literacy',
    subtopic: 'browsers',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Divide total file size by speed.' }],
    ...S,
  }),

  pattern({
    sequence: [
      { id: 'e1', text: 'Move Forward 1 step' },
      { id: 'e2', text: 'Turn Right 90 degrees' },
      { id: 'e3', text: 'Move Forward 1 step' },
      { id: 'e4', text: 'Turn Right 90 degrees' },
    ],
    interaction: 'complete-sequence',
    candidates: [
      { id: 'c1', text: 'Move Forward 1 step' },
      { id: 'c2', text: 'Turn Left 90 degrees' },
      { id: 'c3', text: 'Stop Execution' },
      { id: 'c4', text: 'Jump High' },
    ],
    answer: { type: 'candidate', rule: 'Alternating move and turn commands to walk a square.', acceptableIds: ['c1'] },
    prompt: 'In a robot square-walking algorithm, identify the next command: Move Forward, Turn Right, Move Forward, Turn Right, …',
    explanation: 'The pattern alternates Move Forward and Turn Right to complete four sides.',
    objective: 'Predict the next command step in a block coding loop pattern.',
    topic: 'programming',
    subtopic: 'basics',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Notice the alternating pattern between moving and turning.' }],
    ...S,
  }),

  dragDrop({
    items: [
      { id: 'i1', label: '25' },
      { id: 'i2', label: '"Hello"' },
      { id: 'i3', label: 'True' },
      { id: 'i4', label: '3.14' },
      { id: 'i5', label: '"STEM Quest"' },
      { id: 'i6', label: 'False' },
    ],
    zones: [
      { id: 'z_num', label: 'Numeric Data' },
      { id: 'z_str', label: 'String/Text Data' },
      { id: 'z_bool', label: 'Boolean Data' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_num' },
      { itemId: 'i2', zoneId: 'z_str' },
      { itemId: 'i3', zoneId: 'z_bool' },
      { itemId: 'i4', zoneId: 'z_num' },
      { itemId: 'i5', zoneId: 'z_str' },
      { itemId: 'i6', zoneId: 'z_bool' },
    ],
    prompt: 'Classify each data value as Numeric Data, String/Text Data, or Boolean Data.',
    explanation: '25 and 3.14 are numeric; text inside quotes are strings; True and False are Boolean values.',
    objective: 'Classify primitive programming data types.',
    topic: 'programming',
    subtopic: 'basics',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Values enclosed in quotation marks are strings.' }],
    ...S,
  }),

  fillComplete({
    template: 'To protect your online account from unauthorized access, you should set a strong ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'security secret', maxLength: 12 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['password', 'passcode'] }],
    prompt: 'To protect your online account from unauthorized access, you should set a strong ___.',
    explanation: 'Passwords serve as secret credentials authenticating account ownership.',
    objective: 'Identify passwords as fundamental user credentials.',
    topic: 'digital-literacy',
    subtopic: 'safety',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'A secret word or combination used to sign into accounts.' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'CPU chip' },
      { id: 'i2', label: 'Computer Monitor' },
      { id: 'i3', label: 'RAM stick' },
      { id: 'i4', label: 'Keyboard' },
      { id: 'i5', label: 'Motherboard' },
      { id: 'i6', label: 'USB Mouse' },
    ],
    categories: [
      { id: 'c_int', label: 'Internal Component' },
      { id: 'c_ext', label: 'External Peripheral' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_int' },
      { itemId: 'i2', categoryId: 'c_ext' },
      { itemId: 'i3', categoryId: 'c_int' },
      { itemId: 'i4', categoryId: 'c_ext' },
      { itemId: 'i5', categoryId: 'c_int' },
      { itemId: 'i6', categoryId: 'c_ext' },
    ],
    prompt: 'Sort each item as an Internal Component or an External Peripheral.',
    explanation: 'Internal components (CPU, RAM, motherboard) sit inside the chassis; peripherals (monitor, keyboard, mouse) connect externally.',
    objective: 'Distinguish internal PC parts from external peripherals.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Is it installed inside the main tower or plugged in on your desk?' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'Cloud Backup' },
      { id: 'l2', text: 'Cloud Syncing' },
      { id: 'l3', text: 'Cloud Sharing' },
      { id: 'l4', text: 'Cloud Accessibility' },
    ],
    rightItems: [
      { id: 'r1', text: 'Protects against local disk failure' },
      { id: 'r2', text: 'Keeps files identical on all devices' },
      { id: 'r3', text: 'Allows collaborative team editing' },
      { id: 'r4', text: 'Enables access from any connected PC' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each cloud computing service benefit to its description.',
    explanation: 'Backups safeguard data, syncing updates devices, sharing enables teamwork, and accessibility allows login anywhere.',
    objective: 'Relate cloud storage benefits to their practical uses.',
    topic: 'digital-tools',
    subtopic: 'spreadsheets',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which benefit allows multiple users to edit the same file online?' }],
    ...S,
  }),

  memory({
    cards: [
      { id: 'c1', text: 'Ctrl + C' },
      { id: 'c2', text: 'Copy text/file' },
      { id: 'c3', text: 'Ctrl + V' },
      { id: 'c4', text: 'Paste copied item' },
      { id: 'c5', text: 'Ctrl + Z' },
      { id: 'c6', text: 'Undo last action' },
      { id: 'c7', text: 'Ctrl + S' },
      { id: 'c8', text: 'Save current document' },
    ],
    groups: [
      { groupId: 'g1', cardIds: ['c1', 'c2'] },
      { groupId: 'g2', cardIds: ['c3', 'c4'] },
      { groupId: 'g3', cardIds: ['c5', 'c6'] },
      { groupId: 'g4', cardIds: ['c7', 'c8'] },
    ],
    revealSeconds: 12,
    recallPrompt: 'Remember each shortcut key combination with its action.',
    deckType: 'pairs',
    prompt: 'Memorise each keyboard shortcut with its action, then match the pairs.',
    explanation: 'Ctrl+C copies, Ctrl+V pastes, Ctrl+Z undoes changes, and Ctrl+S saves work.',
    objective: 'Match standard computer keyboard shortcuts to operations.',
    topic: 'digital-literacy',
    subtopic: 'browsers',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Pair the shortcut key with what it does.' }],
    ...S,
  }),

  fillComplete({
    template: 'A step-by-step set of instructions for solving a problem is called an ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'algorithm term', maxLength: 12 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['algorithm', 'algorithms'] }],
    prompt: 'A step-by-step set of instructions for solving a problem is called an ___.',
    explanation: 'An algorithm provides clear, ordered steps to achieve a specific goal or solve a problem.',
    objective: 'Define the term algorithm in computer science.',
    topic: 'programming',
    subtopic: 'basics',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'It starts with the letter A and describes step-by-step code rules.' }],
    ...S,
  }),

  dragDrop({
    items: [
      { id: 'i1', label: 'Touchscreen' },
      { id: 'i2', label: 'Webcam' },
      { id: 'i3', label: 'Printer' },
      { id: 'i4', label: 'Headphones' },
      { id: 'i5', label: 'Barcode Scanner' },
      { id: 'i6', label: 'Projector' },
    ],
    zones: [
      { id: 'z_in', label: 'Input Device' },
      { id: 'z_out', label: 'Output Device' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_in' },
      { itemId: 'i2', zoneId: 'z_in' },
      { itemId: 'i3', zoneId: 'z_out' },
      { itemId: 'i4', zoneId: 'z_out' },
      { itemId: 'i5', zoneId: 'z_in' },
      { itemId: 'i6', zoneId: 'z_out' },
    ],
    prompt: 'Classify each hardware item as an Input Device or an Output Device.',
    explanation: 'Touchscreens, webcams, and barcode scanners capture data into the system (input). Printers, headphones, and projectors present data to users (output).',
    objective: 'Classify digital peripherals by data direction.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Does it send data to the computer or display/play output?' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'Ethernet cable' },
      { id: 'i2', label: 'Wi-Fi 6' },
      { id: 'i3', label: 'USB network tether' },
      { id: 'i4', label: 'Bluetooth' },
      { id: 'i5', label: 'Fiber optic cable' },
      { id: 'i6', label: '5G Mobile network' },
    ],
    categories: [
      { id: 'c_wired', label: 'Wired Connection' },
      { id: 'c_wireless', label: 'Wireless Connection' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_wired' },
      { itemId: 'i2', categoryId: 'c_wireless' },
      { itemId: 'i3', categoryId: 'c_wired' },
      { itemId: 'i4', categoryId: 'c_wireless' },
      { itemId: 'i5', categoryId: 'c_wired' },
      { itemId: 'i6', categoryId: 'c_wireless' },
    ],
    prompt: 'Sort each network link type into Wired Connection or Wireless Connection.',
    explanation: 'Ethernet cables, USB tethers, and fiber optics use physical cables. Wi-Fi, Bluetooth, and cellular 5G transmit via radio signals.',
    objective: 'Distinguish wired from wireless communication mediums.',
    topic: 'digital-literacy',
    subtopic: 'browsers',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Does data travel through physical cables or radio waves?' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'For Loop' },
      { id: 'l2', text: 'While Loop' },
      { id: 'l3', text: 'Infinite Loop' },
      { id: 'l4', text: 'Nested Loop' },
    ],
    rightItems: [
      { id: 'r1', text: 'Repeats a fixed count of times' },
      { id: 'r2', text: 'Repeats while a condition is true' },
      { id: 'r3', text: 'Repeats endlessly without stopping' },
      { id: 'r4', text: 'A loop placed inside another loop' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each programming loop structure to its behavior.',
    explanation: 'For loops run a set count, while loops check a condition, infinite loops lack an exit condition, and nested loops sit inside other loops.',
    objective: 'Identify programming loop types and behaviors.',
    topic: 'programming',
    subtopic: 'basics',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which loop runs a specific number of times known in advance?' }],
    ...S,
  }),

  fillComplete({
    template: 'Malicious software designed to damage computer systems or steal data is called a computer ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'threat term', maxLength: 10 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['virus', 'malware'] }],
    prompt: 'Malicious software designed to damage computer systems or steal data is called a computer ___.',
    explanation: 'A computer virus or malware infects systems to cause harm or compromise privacy.',
    objective: 'Define computer viruses as security threats.',
    topic: 'digital-literacy',
    subtopic: 'safety',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'A common word for harmful software that infects computers.' }],
    ...S,
  }),

  ordering({
    items: [
      { id: 'o1', label: 'Data Collection' },
      { id: 'o2', label: 'Data Storage' },
      { id: 'o3', label: 'Data Analysis' },
      { id: 'o4', label: 'Data Visualisation' },
    ],
    order: ['o1', 'o2', 'o3', 'o4'],
    prompt: 'Arrange the stages of the data processing lifecycle in order.',
    explanation: 'Data must be collected first, stored safely, analyzed to find patterns, and finally visualised in charts or reports.',
    objective: 'Order the stages of data processing.',
    topic: 'data-ai',
    subtopic: 'data-basics',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Gathering data comes before analyzing or creating charts.' }],
    ...S,
  }),

  numberLogic({
    problem: 'If a tablet screen consumes 4 watts and its processor consumes 6 watts, how many total watts of power are consumed?',
    answerFormat: 'integer',
    answer: { type: 'exact', value: 10 },
    prompt: 'If a tablet screen consumes 4 watts and its processor consumes 6 watts, how many total watts of power are consumed?',
    explanation: '4 watts + 6 watts = 10 watts total power.',
    objective: 'Calculate total power consumption of hardware parts.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Add the power values of both components together.' }],
    ...S,
  }),

  pattern({
    sequence: [
      { id: 'e1', text: '2 GB RAM' },
      { id: 'e2', text: '4 GB RAM' },
      { id: 'e3', text: '8 GB RAM' },
      { id: 'e4', text: '16 GB RAM' },
    ],
    interaction: 'complete-sequence',
    candidates: [
      { id: 'c1', text: '20 GB RAM' },
      { id: 'c2', text: '32 GB RAM' },
      { id: 'c3', text: '24 GB RAM' },
      { id: 'c4', text: '64 GB RAM' },
    ],
    answer: { type: 'candidate', rule: 'Doubling capacity steps for computer memory.', acceptableIds: ['c2'] },
    prompt: 'Predict the next standard RAM capacity step in the sequence: 2 GB, 4 GB, 8 GB, 16 GB, …',
    explanation: 'Standard RAM capacities double with each generation step: 16 × 2 = 32 GB.',
    objective: 'Predict binary doubling memory capacities.',
    topic: 'computing',
    subtopic: 'hardware',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Double the previous capacity.' }],
    ...S,
  }),

  memory({
    cards: [
      { id: 'c1', text: 'SaaS' },
      { id: 'c2', text: 'Software delivered over cloud' },
      { id: 'c3', text: 'Cloud Storage' },
      { id: 'c4', text: 'Remote online file storage' },
      { id: 'c5', text: 'Data Center' },
      { id: 'c6', text: 'Facility housing cloud servers' },
      { id: 'c7', text: 'Bandwidth' },
      { id: 'c8', text: 'Maximum network transfer rate' },
    ],
    groups: [
      { groupId: 'g1', cardIds: ['c1', 'c2'] },
      { groupId: 'g2', cardIds: ['c3', 'c4'] },
      { groupId: 'g3', cardIds: ['c5', 'c6'] },
      { groupId: 'g4', cardIds: ['c7', 'c8'] },
    ],
    revealSeconds: 12,
    recallPrompt: 'Remember each cloud computing term with its definition.',
    deckType: 'pairs',
    prompt: 'Memorise each cloud technology term with its description, then match the pairs.',
    explanation: 'SaaS delivers web apps, cloud storage keeps remote files, data centers host servers, and bandwidth measures transfer rate.',
    objective: 'Match cloud computing concepts to definitions.',
    topic: 'digital-tools',
    subtopic: 'spreadsheets',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which acronym stands for Software as a Service?' }],
    ...S,
  }),

  dragDrop({
    items: [
      { id: 'i1', label: 'Single 0 or 1' },
      { id: 'i2', label: 'Group of 8 bits' },
      { id: 'i3', label: 'Binary Digit' },
      { id: 'i4', label: 'Represents 1 character' },
      { id: 'i5', label: 'Smallest unit of data' },
      { id: 'i6', label: 'Unit used for byte storage' },
    ],
    zones: [
      { id: 'z_bit', label: 'Bit Concept' },
      { id: 'z_byte', label: 'Byte Concept' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_bit' },
      { itemId: 'i2', zoneId: 'z_byte' },
      { itemId: 'i3', zoneId: 'z_bit' },
      { itemId: 'i4', zoneId: 'z_byte' },
      { itemId: 'i5', zoneId: 'z_bit' },
      { itemId: 'i6', zoneId: 'z_byte' },
    ],
    prompt: 'Classify each data representation description as a Bit Concept or a Byte Concept.',
    explanation: 'A bit is a single binary digit (0 or 1, smallest unit). A byte contains 8 bits and represents one text character.',
    objective: 'Distinguish bits from bytes in data representation.',
    topic: 'computing',
    subtopic: 'data-representation',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'A byte is made up of 8 bits.' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'Voice assistant speech recognition' },
      { id: 'i2', label: 'Facial recognition camera unlocking' },
      { id: 'i3', label: 'Language translation app' },
      { id: 'i4', label: 'Autonomous vehicle obstacle detection' },
      { id: 'i5', label: 'Text chatbot response generation' },
      { id: 'i6', label: 'Medical X-ray image scan analysis' },
    ],
    categories: [
      { id: 'c_nlp', label: 'Natural Language AI' },
      { id: 'c_cv', label: 'Computer Vision AI' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_nlp' },
      { itemId: 'i2', categoryId: 'c_cv' },
      { itemId: 'i3', categoryId: 'c_nlp' },
      { itemId: 'i4', categoryId: 'c_cv' },
      { itemId: 'i5', categoryId: 'c_nlp' },
      { itemId: 'i6', categoryId: 'c_cv' },
    ],
    prompt: 'Sort each artificial intelligence application into Natural Language AI or Computer Vision AI.',
    explanation: 'Natural language AI handles spoken or written text. Computer vision AI analyzes photos, video feeds, and visual sensor inputs.',
    objective: 'Categorise AI applications by input modality.',
    topic: 'data-ai',
    subtopic: 'ai-basics',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Does the application process text/speech or visual images/video?' }],
    ...S,
  }),

  fillComplete({
    template: 'The keyboard shortcut to copy selected text on Windows is Ctrl + ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'shortcut key letter', maxLength: 2 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['c', 'C'] }],
    prompt: 'The keyboard shortcut to copy selected text on Windows is Ctrl + ___.',
    explanation: 'Ctrl + C copies highlighted text or files to the system clipboard.',
    objective: 'Recall standard keyboard shortcuts.',
    topic: 'digital-literacy',
    subtopic: 'browsers',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'The key letter stands for Copy.' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'Database Table' },
      { id: 'l2', text: 'Record / Row' },
      { id: 'l3', text: 'Field / Column' },
      { id: 'l4', text: 'Primary Key' },
    ],
    rightItems: [
      { id: 'r1', text: 'Grid containing structured data' },
      { id: 'r2', text: 'Single complete entry in a table' },
      { id: 'r3', text: 'Specific data attribute category' },
      { id: 'r4', text: 'Unique ID for each record' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each database term to its structural role.',
    explanation: 'Tables store data in grids, records represent individual entries, fields represent attributes, and primary keys uniquely identify rows.',
    objective: 'Match relational database components to definitions.',
    topic: 'data-ai',
    subtopic: 'data-basics',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which key uniquely identifies a single database row?' }],
    ...S,
  }),

  ordering({
    items: [
      { id: 'o1', label: 'Verify URL begins with https://' },
      { id: 'o2', label: 'Check vendor ratings and reviews' },
      { id: 'o3', label: 'Select secure payment gateway' },
      { id: 'o4', label: 'Save receipt confirmation email' },
    ],
    order: ['o1', 'o2', 'o3', 'o4'],
    prompt: 'Order the steps for safe online transaction habits.',
    explanation: 'Check web security, verify merchant reputation, pay via encrypted gateway, and keep purchase receipts.',
    objective: 'Order safety steps for online commerce.',
    topic: 'digital-literacy',
    subtopic: 'safety',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Always confirm HTTPS encryption before entering payment details.' }],
    ...S,
  }),

  numberLogic({
    problem: 'An HD video file takes 1000 MB of storage space. How many gigabytes (GB) is this equal to if 1 GB = 1000 MB?',
    answerFormat: 'integer',
    answer: { type: 'exact', value: 1 },
    prompt: 'An HD video file takes 1000 MB of storage space. How many gigabytes (GB) is this equal to if 1 GB = 1000 MB?',
    explanation: '1000 MB ÷ 1000 = 1 GB.',
    objective: 'Convert megabytes to gigabytes.',
    topic: 'computing',
    subtopic: 'data-representation',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Divide the number of megabytes by 1000.' }],
    ...S,
  }),

  pattern({
    sequence: [
      { id: 'e1', text: 'Oval: Start' },
      { id: 'e2', text: 'Rectangle: Process' },
      { id: 'e3', text: 'Diamond: Decision' },
      { id: 'e4', text: 'Rectangle: Process' },
    ],
    interaction: 'complete-sequence',
    candidates: [
      { id: 'c1', text: 'Oval: End' },
      { id: 'c2', text: 'Circle: Loop' },
      { id: 'c3', text: 'Triangle: Stop' },
      { id: 'c4', text: 'Square: Break' },
    ],
    answer: { type: 'candidate', rule: 'Standard flowchart ending symbol.', acceptableIds: ['c1'] },
    prompt: 'Identify the final symbol to conclude a standard algorithm flowchart: Start (Oval) -> Process -> Decision -> Process -> …',
    explanation: 'Flowcharts begin and end with oval terminator symbols (Start / End).',
    objective: 'Identify standard flowchart symbols.',
    topic: 'programming',
    subtopic: 'basics',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'The end symbol matches the start symbol shape.' }],
    ...S,
  }),

  dragDrop({
    items: [
      { id: 'i1', label: 'Windows 11' },
      { id: 'i2', label: 'Android 14' },
      { id: 'i3', label: 'macOS Sonoma' },
      { id: 'i4', label: 'iOS 17' },
      { id: 'i5', label: 'Ubuntu Linux' },
      { id: 'i6', label: 'iPadOS' },
    ],
    zones: [
      { id: 'z_desk', label: 'Desktop OS' },
      { id: 'z_mob', label: 'Mobile OS' },
    ],
    mappings: [
      { itemId: 'i1', zoneId: 'z_desk' },
      { itemId: 'i2', zoneId: 'z_mob' },
      { itemId: 'i3', zoneId: 'z_desk' },
      { itemId: 'i4', zoneId: 'z_mob' },
      { itemId: 'i5', zoneId: 'z_desk' },
      { itemId: 'i6', zoneId: 'z_mob' },
    ],
    prompt: 'Classify each operating system as a Desktop OS or a Mobile OS.',
    explanation: 'Windows, macOS, and Linux power desktop/laptop computers. Android, iOS, and iPadOS power smartphones and tablets.',
    objective: 'Classify operating systems by target device platform.',
    topic: 'computing',
    subtopic: 'software',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Does the OS run on desktop computers or smartphones?' }],
    ...S,
  }),

  fillComplete({
    template: 'In a spreadsheet grid, vertical columns are identified by letters and horizontal rows are identified by ___.',
    blanks: [{ id: 'b1', type: 'text', label: 'row identifier', maxLength: 10 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['numbers', 'number'] }],
    prompt: 'In a spreadsheet grid, vertical columns are identified by letters and horizontal rows are identified by ___.',
    explanation: 'Spreadsheets use letters for columns (A, B, C...) and numbers for rows (1, 2, 3...).',
    objective: 'Identify spreadsheet row labeling conventions.',
    topic: 'digital-tools',
    subtopic: 'spreadsheets',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Rows are labeled 1, 2, 3...' }],
    ...S,
  }),

  sorting({
    items: [
      { id: 'i1', label: 'archive.zip' },
      { id: 'i2', label: 'photo.bmp' },
      { id: 'i3', label: 'backup.rar' },
      { id: 'i4', label: 'recording.wav' },
      { id: 'i5', label: 'data.7z' },
      { id: 'i6', label: 'document.txt' },
    ],
    categories: [
      { id: 'c_comp', label: 'Compressed File' },
      { id: 'c_uncomp', label: 'Uncompressed File' },
    ],
    assignments: [
      { itemId: 'i1', categoryId: 'c_comp' },
      { itemId: 'i2', categoryId: 'c_uncomp' },
      { itemId: 'i3', categoryId: 'c_comp' },
      { itemId: 'i4', categoryId: 'c_uncomp' },
      { itemId: 'i5', categoryId: 'c_comp' },
      { itemId: 'i6', categoryId: 'c_uncomp' },
    ],
    prompt: 'Sort each file into Compressed File archive or Uncompressed File.',
    explanation: '.zip, .rar, and .7z are compressed file archives designed to reduce storage space. .bmp, .wav, and .txt are uncompressed formats.',
    objective: 'Identify compressed archive file formats.',
    topic: 'digital-literacy',
    subtopic: 'file-types',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Look for archive extensions like .zip or .rar.' }],
    ...S,
  }),

  matching({
    leftItems: [
      { id: 'l1', text: 'Phishing' },
      { id: 'l2', text: 'Ransomware' },
      { id: 'l3', text: 'Spyware' },
      { id: 'l4', text: 'Firewall' },
    ],
    rightItems: [
      { id: 'r1', text: 'Fake emails tricking users for passwords' },
      { id: 'r2', text: 'Encrypts files and demands ransom' },
      { id: 'r3', text: 'Secretly tracks user activity and keystrokes' },
      { id: 'r4', text: 'Security barrier blocking unsafe traffic' },
    ],
    pairs: [
      { leftId: 'l1', rightId: 'r1' },
      { leftId: 'l2', rightId: 'r2' },
      { leftId: 'l3', rightId: 'r3' },
      { leftId: 'l4', rightId: 'r4' },
    ],
    prompt: 'Match each cybersecurity term to its description.',
    explanation: 'Phishing tricks users into giving data, ransomware locks files, spyware tracks activity secretly, and firewalls protect network perimeters.',
    objective: 'Match cybersecurity concepts to definitions.',
    topic: 'digital-literacy',
    subtopic: 'safety',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which defense monitors incoming and outgoing network traffic?' }],
    ...S,
  }),

  memory({
    cards: [
      { id: 'c1', text: 'Raster PNG' },
      { id: 'c2', text: 'Pixel-based image' },
      { id: 'c3', text: 'Vector SVG' },
      { id: 'c4', text: 'Scalable graphic' },
      { id: 'c5', text: 'GIF' },
      { id: 'c6', text: 'Animated image format' },
      { id: 'c7', text: 'JPEG' },
      { id: 'c8', text: 'Lossy photo format' },
    ],
    groups: [
      { groupId: 'g1', cardIds: ['c1', 'c2'] },
      { groupId: 'g2', cardIds: ['c3', 'c4'] },
      { groupId: 'g3', cardIds: ['c5', 'c6'] },
      { groupId: 'g4', cardIds: ['c7', 'c8'] },
    ],
    revealSeconds: 12,
    recallPrompt: 'Remember each graphic format with its characteristics.',
    deckType: 'pairs',
    prompt: 'Memorise each image format with its characteristic, then match the pairs.',
    explanation: 'PNG uses pixels, SVG uses scalable vectors, GIF supports simple animations, and JPEG compresses photo images.',
    objective: 'Match digital graphic formats to properties.',
    topic: 'digital-literacy',
    subtopic: 'file-types',
    difficulty: 2,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Which format scales infinitely without losing crispness?' }],
    ...S,
  }),

  fillComplete({
    template: 'A high-speed internet cable made of glass or plastic strands that transmit data using light is a ___ optic cable.',
    blanks: [{ id: 'b1', type: 'text', label: 'cable type', maxLength: 10 }],
    answers: [{ blankId: 'b1', type: 'text', accepted: ['fiber', 'fibre'] }],
    prompt: 'A high-speed internet cable made of glass or plastic strands that transmit data using light is a ___ optic cable.',
    explanation: 'Fiber optic cables transmit data as light pulses through glass strands.',
    objective: 'Identify fiber optic cables.',
    topic: 'digital-literacy',
    subtopic: 'browsers',
    difficulty: 1,
    gradeMin: 6,
    gradeMax: 7,
    hints: [{ level: 1, text: 'Starts with F and uses light to send data.' }],
    ...S,
  }),
]


